"""GENERATED by packages/service-template/scaffold.py from docs/endpoint-catalogue.md — do not edit.

Phase-1 operations owned by this service. Until an operation is implemented, it verifies the caller's
internal token and answers 501 /problems/not-yet-built. Replace a stub by adding a real route with the
same method and path in app/api/routes.py; stubs are only registered for paths not already routed."""
from fastapi import APIRouter, Depends

from epfo_auth import Actor, require_actor
from epfo_observability import Problem

router = APIRouter()

OPERATIONS = ['GET /office/rti-requests', 'POST /office/rti-requests', 'POST /public/grievances', 'POST /integrations/cpgrams/grievances', 'GET /members/me/grievances', 'POST /members/me/grievances', 'POST /public/grievances/status-lookups', 'POST /office/rti-requests/{requestId}/replies', 'GET /grievances/{grievanceId}', 'POST /grievances/{grievanceId}/documents', 'POST /grievances/{grievanceId}/escalations', 'POST /grievances/{grievanceId}/evidence-links', 'POST /grievances/{grievanceId}/feedback', 'POST /grievances/{grievanceId}/messages', 'POST /grievances/{grievanceId}/office-transfers', 'POST /grievances/{grievanceId}/reminders', 'POST /grievances/{grievanceId}/reopen-requests', 'POST /grievances/{grievanceId}/resolution']

@router.api_route("/api/v1/office/rti-requests", methods=["GET"], include_in_schema=False)
async def get_office_rti_requests(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "The office's RTI applications and their reply due dates")


@router.api_route("/api/v1/office/rti-requests", methods=["POST"], include_in_schema=False)
async def post_office_rti_requests(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Register an RTI application received (post, counter or the RTI portal)")


@router.api_route("/api/v1/public/grievances", methods=["POST"], include_in_schema=False)
async def post_public_grievances(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Grievance intake from a non-logged-in person (OTP-verified contact)")


@router.api_route("/api/v1/integrations/cpgrams/grievances", methods=["POST"], include_in_schema=False)
async def post_integrations_cpgrams_grievances(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "CPGRAMS grievance feed (signed)")


@router.api_route("/api/v1/members/me/grievances", methods=["GET"], include_in_schema=False)
async def get_members_me_grievances(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "List own grievances")


@router.api_route("/api/v1/members/me/grievances", methods=["POST"], include_in_schema=False)
async def post_members_me_grievances(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Member registers grievance linked to a claim (Journey C1)")


@router.api_route("/api/v1/public/grievances/status-lookups", methods=["POST"], include_in_schema=False)
async def post_public_grievances_status_lookups(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Grievance status by registration number (OTP proof)")


@router.api_route("/api/v1/office/rti-requests/{requestId}/replies", methods=["POST"], include_in_schema=False)
async def post_office_rti_requests_requestId_replies(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Record RTI replies")


@router.api_route("/api/v1/grievances/{grievanceId}", methods=["GET"], include_in_schema=False)
async def get_grievances_grievanceId(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Grievance detail (only the assigned office can read the body — Journey C2)")


@router.api_route("/api/v1/grievances/{grievanceId}/documents", methods=["POST"], include_in_schema=False)
async def post_grievances_grievanceId_documents(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Attach a synthetic document (object store, malware-scan stub, Journey C1)")


@router.api_route("/api/v1/grievances/{grievanceId}/escalations", methods=["POST"], include_in_schema=False)
async def post_grievances_grievanceId_escalations(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Escalate to next supervisory tier (Journey C4)")


@router.api_route("/api/v1/grievances/{grievanceId}/evidence-links", methods=["POST"], include_in_schema=False)
async def post_grievances_grievanceId_evidence_links(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Officer attaches case-linked evidence (Journey C3)")


@router.api_route("/api/v1/grievances/{grievanceId}/feedback", methods=["POST"], include_in_schema=False)
async def post_grievances_grievanceId_feedback(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Closure feedback / satisfaction")


@router.api_route("/api/v1/grievances/{grievanceId}/messages", methods=["POST"], include_in_schema=False)
async def post_grievances_grievanceId_messages(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Reply / message")


@router.api_route("/api/v1/grievances/{grievanceId}/office-transfers", methods=["POST"], include_in_schema=False)
async def post_grievances_grievanceId_office_transfers(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Transfer a grievance to another office")


@router.api_route("/api/v1/grievances/{grievanceId}/reminders", methods=["POST"], include_in_schema=False)
async def post_grievances_grievanceId_reminders(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Complainant reminder on an overdue grievance")


@router.api_route("/api/v1/grievances/{grievanceId}/reopen-requests", methods=["POST"], include_in_schema=False)
async def post_grievances_grievanceId_reopen_requests(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Complainant requests reopening")


@router.api_route("/api/v1/grievances/{grievanceId}/resolution", methods=["POST"], include_in_schema=False)
async def post_grievances_grievanceId_resolution(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Resolve with reason (Journey C4)")
