"""GENERATED by packages/service-template/scaffold.py from docs/endpoint-catalogue.md — do not edit.

Phase-1 operations owned by this service. Until an operation is implemented, it verifies the caller's
internal token and answers 501 /problems/not-yet-built. Replace a stub by adding a real route with the
same method and path in app/api/routes.py; stubs are only registered for paths not already routed."""
from fastapi import APIRouter, Depends

from epfo_auth import Actor, require_actor
from epfo_observability import Problem

router = APIRouter()

OPERATIONS = ['GET /members/me/grievances', 'POST /members/me/grievances', 'GET /grievances/{grievanceId}', 'POST /grievances/{grievanceId}/documents', 'POST /grievances/{grievanceId}/escalations', 'POST /grievances/{grievanceId}/evidence-links', 'POST /grievances/{grievanceId}/messages', 'POST /grievances/{grievanceId}/reopen-requests', 'POST /grievances/{grievanceId}/resolution']

@router.api_route("/api/v1/members/me/grievances", methods=["GET"], include_in_schema=False)
async def get_members_me_grievances(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "List own grievances")


@router.api_route("/api/v1/members/me/grievances", methods=["POST"], include_in_schema=False)
async def post_members_me_grievances(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Member registers grievance linked to a claim (Journey C1)")


@router.api_route("/api/v1/grievances/{grievanceId}", methods=["GET"], include_in_schema=False)
async def get_grievances_grievanceId(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Grievance detail (only the assigned office can read the body — Journey C2)")


@router.api_route("/api/v1/grievances/{grievanceId}/documents", methods=["POST"], include_in_schema=False)
async def post_grievances_grievanceId_documents(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Attach a synthetic document (object store, malware-scan stub, Journey C1)")


@router.api_route("/api/v1/grievances/{grievanceId}/escalations", methods=["POST"], include_in_schema=False)
async def post_grievances_grievanceId_escalations(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Escalate to next supervisory tier (Journey C4)")


@router.api_route("/api/v1/grievances/{grievanceId}/evidence-links", methods=["POST"], include_in_schema=False)
async def post_grievances_grievanceId_evidence_links(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Officer attaches case-linked evidence (Journey C3)")


@router.api_route("/api/v1/grievances/{grievanceId}/messages", methods=["POST"], include_in_schema=False)
async def post_grievances_grievanceId_messages(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Reply / message")


@router.api_route("/api/v1/grievances/{grievanceId}/reopen-requests", methods=["POST"], include_in_schema=False)
async def post_grievances_grievanceId_reopen_requests(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Complainant requests reopening")


@router.api_route("/api/v1/grievances/{grievanceId}/resolution", methods=["POST"], include_in_schema=False)
async def post_grievances_grievanceId_resolution(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Resolve with reason (Journey C4)")
