"""GENERATED by packages/service-template/scaffold.py from docs/endpoint-catalogue.md — do not edit.

Phase-1 operations owned by this service. Until an operation is implemented, it verifies the caller's
internal token and answers 501 /problems/not-yet-built. Replace a stub by adding a real route with the
same method and path in app/api/routes.py; stubs are only registered for paths not already routed."""
from fastapi import APIRouter, Depends

from epfo_auth import Actor, require_actor
from epfo_observability import Problem

router = APIRouter()

OPERATIONS = ['GET /hrm/me', 'GET /office/work-queue', 'GET /public/offices', 'GET /office/cases/{caseId}', 'POST /office/cases/{caseId}/assignments', 'POST /office/cases/{caseId}/decisions', 'POST /office/cases/{caseId}/recommendations', 'POST /office/cases/{caseId}/second-approvals']

@router.api_route("/api/v1/hrm/me", methods=["GET"], include_in_schema=False)
async def get_hrm_me(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "HRM staff profile and assignment metadata (interface 15)")


@router.api_route("/api/v1/office/work-queue", methods=["GET"], include_in_schema=False)
async def get_office_work_queue(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Jurisdiction-filtered task queue")


@router.api_route("/api/v1/public/offices", methods=["GET"], include_in_schema=False)
async def get_public_offices(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Office locator by state/district/pincode")


@router.api_route("/api/v1/office/cases/{caseId}", methods=["GET"], include_in_schema=False)
async def get_office_cases_caseId(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Case detail")


@router.api_route("/api/v1/office/cases/{caseId}/assignments", methods=["POST"], include_in_schema=False)
async def post_office_cases_caseId_assignments(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Assign")


@router.api_route("/api/v1/office/cases/{caseId}/decisions", methods=["POST"], include_in_schema=False)
async def post_office_cases_caseId_decisions(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Decision → CaseDecisionSubmitted.v1")


@router.api_route("/api/v1/office/cases/{caseId}/recommendations", methods=["POST"], include_in_schema=False)
async def post_office_cases_caseId_recommendations(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Dealing-hand recommendation")


@router.api_route("/api/v1/office/cases/{caseId}/second-approvals", methods=["POST"], include_in_schema=False)
async def post_office_cases_caseId_second_approvals(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Dual control for high-value / high-risk cases")
