"""GENERATED by packages/service-template/scaffold.py from docs/endpoint-catalogue.md — do not edit.

Phase-1 operations owned by this service. Until an operation is implemented, it verifies the caller's
internal token and answers 501 /problems/not-yet-built. Replace a stub by adding a real route with the
same method and path in app/api/routes.py; stubs are only registered for paths not already routed."""
from fastapi import APIRouter, Depends

from epfo_auth import Actor, require_actor
from epfo_observability import Problem

router = APIRouter()

OPERATIONS = ['GET /hrm/me', 'GET /office/stopped-cases', 'GET /office/work-queue', 'GET /public/offices', 'GET /employers/me/pending-approvals', 'POST /office/system/locks/{lockId}/release', 'GET /office/cases/{caseId}', 'POST /office/cases/{caseId}/assignments', 'POST /office/cases/{caseId}/decisions', 'POST /office/cases/{caseId}/recommendations', 'POST /office/cases/{caseId}/restarts', 'POST /office/cases/{caseId}/second-approvals', 'POST /office/cases/{caseId}/stops', 'POST /office/freeze-cases/{caseId}/verifications', 'GET /office/members/{uan}/locks', 'POST /office/cases/{caseId}/documents/{docId}/attestation-views']

@router.api_route("/api/v1/hrm/me", methods=["GET"], include_in_schema=False)
async def get_hrm_me(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "HRM staff profile and assignment metadata (interface 15)")


@router.api_route("/api/v1/office/stopped-cases", methods=["GET"], include_in_schema=False)
async def get_office_stopped_cases(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Stopped claims of the office")


@router.api_route("/api/v1/office/work-queue", methods=["GET"], include_in_schema=False)
async def get_office_work_queue(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Jurisdiction-filtered task queue")


@router.api_route("/api/v1/public/offices", methods=["GET"], include_in_schema=False)
async def get_public_offices(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Office locator by state/district/pincode")


@router.api_route("/api/v1/employers/me/pending-approvals", methods=["GET"], include_in_schema=False)
async def get_employers_me_pending_approvals(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Items awaiting DSC/e-sign (KYC, transfers, claims, JD)")


@router.api_route("/api/v1/office/system/locks/{lockId}/release", methods=["POST"], include_in_schema=False)
async def post_office_system_locks_lockId_release(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Supervised release of an orphaned lock (reason required) → LockReleased.v1 (tracker: 'Unable to lock")


@router.api_route("/api/v1/office/cases/{caseId}", methods=["GET"], include_in_schema=False)
async def get_office_cases_caseId(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Case detail")


@router.api_route("/api/v1/office/cases/{caseId}/assignments", methods=["POST"], include_in_schema=False)
async def post_office_cases_caseId_assignments(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Assign")


@router.api_route("/api/v1/office/cases/{caseId}/decisions", methods=["POST"], include_in_schema=False)
async def post_office_cases_caseId_decisions(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Decision → CaseDecisionSubmitted.v1; only the final level rejects, an intermediate 'Recommend to Rej")


@router.api_route("/api/v1/office/cases/{caseId}/recommendations", methods=["POST"], include_in_schema=False)
async def post_office_cases_caseId_recommendations(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Initiator's 'Recommend to Approve / to Reject' with the account status (Operative / Inoperative / Do")


@router.api_route("/api/v1/office/cases/{caseId}/restarts", methods=["POST"], include_in_schema=False)
async def post_office_cases_caseId_restarts(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Restart Claim from the stopped-claims list")


@router.api_route("/api/v1/office/cases/{caseId}/second-approvals", methods=["POST"], include_in_schema=False)
async def post_office_cases_caseId_second_approvals(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Dual control for high-value / high-risk cases")


@router.api_route("/api/v1/office/cases/{caseId}/stops", methods=["POST"], include_in_schema=False)
async def post_office_cases_caseId_stops(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Stop Claim Processing with a reason (initiator; a parallel activity must finish first)")


@router.api_route("/api/v1/office/freeze-cases/{caseId}/verifications", methods=["POST"], include_in_schema=False)
async def post_office_freeze_cases_caseId_verifications(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Freeze-case verification step (DA → SS/AO → APFC/RPFC-II → OIC; tier-2 process member_freeze)")


@router.api_route("/api/v1/office/members/{uan}/locks", methods=["GET"], include_in_schema=False)
async def get_office_members_uan_locks(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Active locks on a member ledger (annual accounts, claim adjudication, ECR posting) with owner and ex")


@router.api_route("/api/v1/office/cases/{caseId}/documents/{docId}/attestation-views", methods=["POST"], include_in_schema=False)
async def post_office_cases_caseId_documents_docId_attestation_views(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Record that the caseworker opened the employer-signed PDF / DSC document; enables the approve action")
