"""GENERATED by packages/service-template/scaffold.py from docs/endpoint-catalogue.md — do not edit.

Phase-1 operations owned by this service. Until an operation is implemented, it verifies the caller's
internal token and answers 501 /problems/not-yet-built. Replace a stub by adding a real route with the
same method and path in app/api/routes.py; stubs are only registered for paths not already routed."""
from fastapi import APIRouter, Depends

from epfo_auth import Actor, require_actor
from epfo_observability import Problem

router = APIRouter()

OPERATIONS = ['POST /public/trrn-status-lookups', 'GET /employers/me/challans', 'GET /employers/me/ecr-filings', 'POST /employers/me/ecr-filings', 'GET /members/me/passbook', 'POST /public/demo-calculations/epf', 'POST /partners/sandbox/payroll/ecr-filings', 'GET /employers/me/challans/{trrn}', 'GET /employers/me/ecr-filings/{filingId}', 'GET /employers/me/challans/{trrn}/receipt', 'POST /employers/me/ecr-filings/{filingId}/approvals', 'POST /employers/me/ecr-filings/{filingId}/submissions', 'POST /employers/me/ecr-filings/{filingId}/validations', 'GET /members/me/accounts/{accountLinkId}/passbook']

@router.api_route("/api/v1/public/trrn-status-lookups", methods=["POST"], include_in_schema=False)
async def post_public_trrn_status_lookups(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "TRRN / challan status lookup with wage month, issue/payment times and next step; one-use synthetic d")


@router.api_route("/api/v1/employers/me/challans", methods=["GET"], include_in_schema=False)
async def get_employers_me_challans(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Challan list")


@router.api_route("/api/v1/employers/me/ecr-filings", methods=["GET"], include_in_schema=False)
async def get_employers_me_ecr_filings(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Return filing history")


@router.api_route("/api/v1/employers/me/ecr-filings", methods=["POST"], include_in_schema=False)
async def post_employers_me_ecr_filings(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Create regular monthly ECR (upload / wizard)")


@router.api_route("/api/v1/members/me/passbook", methods=["GET"], include_in_schema=False)
async def get_members_me_passbook(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Passbook across all accounts linked to the caller (no member ID parameter)")


@router.api_route("/api/v1/public/demo-calculations/epf", methods=["POST"], include_in_schema=False)
async def post_public_demo_calculations_epf(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Illustrative EPF contribution calculator")


@router.api_route("/api/v1/partners/sandbox/payroll/ecr-filings", methods=["POST"], include_in_schema=False)
async def post_partners_sandbox_payroll_ecr_filings(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "B2B payroll API ECR upload")


@router.api_route("/api/v1/employers/me/challans/{trrn}", methods=["GET"], include_in_schema=False)
async def get_employers_me_challans_trrn(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Challan detail by TRRN")


@router.api_route("/api/v1/employers/me/ecr-filings/{filingId}", methods=["GET"], include_in_schema=False)
async def get_employers_me_ecr_filings_filingId(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Filing detail and status")


@router.api_route("/api/v1/employers/me/challans/{trrn}/receipt", methods=["GET"], include_in_schema=False)
async def get_employers_me_challans_trrn_receipt(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Payment receipt / CRN")


@router.api_route("/api/v1/employers/me/ecr-filings/{filingId}/approvals", methods=["POST"], include_in_schema=False)
async def post_employers_me_ecr_filings_filingId_approvals(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Signatory approval")


@router.api_route("/api/v1/employers/me/ecr-filings/{filingId}/submissions", methods=["POST"], include_in_schema=False)
async def post_employers_me_ecr_filings_filingId_submissions(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Submit → generate TRRN")


@router.api_route("/api/v1/employers/me/ecr-filings/{filingId}/validations", methods=["POST"], include_in_schema=False)
async def post_employers_me_ecr_filings_filingId_validations(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Schema + business validation")


@router.api_route("/api/v1/members/me/accounts/{accountLinkId}/passbook", methods=["GET"], include_in_schema=False)
async def get_members_me_accounts_accountLinkId_passbook(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Passbook for one linked account; accountLinkId is an opaque ID validated against the caller")
