"""GENERATED by packages/service-template/scaffold.py from docs/endpoint-catalogue.md — do not edit.

Phase-1 operations owned by this service. Until an operation is implemented, it verifies the caller's
internal token and answers 501 /problems/not-yet-built. Replace a stub by adding a real route with the
same method and path in app/api/routes.py; stubs are only registered for paths not already routed."""
from fastapi import APIRouter, Depends

from epfo_auth import Actor, require_actor
from epfo_observability import Problem

router = APIRouter()

OPERATIONS = ['POST /integrations/mock-bank/payment-confirmations', 'POST /integrations/mock-bank/payment-returns', 'POST /employers/me/challans/{trrn}/payment-intents', 'POST /employers/me/demands/{demandId}/payment-intents']

@router.api_route("/api/v1/integrations/mock-bank/payment-confirmations", methods=["POST"], include_in_schema=False)
async def post_integrations_mock_bank_payment_confirmations(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Signed bank confirmation callback")


@router.api_route("/api/v1/integrations/mock-bank/payment-returns", methods=["POST"], include_in_schema=False)
async def post_integrations_mock_bank_payment_returns(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Signed bank return / failure callback")


@router.api_route("/api/v1/employers/me/challans/{trrn}/payment-intents", methods=["POST"], include_in_schema=False)
async def post_employers_me_challans_trrn_payment_intents(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Pay challan via mock bank")


@router.api_route("/api/v1/employers/me/demands/{demandId}/payment-intents", methods=["POST"], include_in_schema=False)
async def post_employers_me_demands_demandId_payment_intents(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Pay a demand (14B / 7Q / admin charges)")
