"""Editorial explanations. These are orientation notes, not eligibility or legal advice.

Activities, interfaces, roles and verified outcomes are imported from repository sources
by build.py. Keep these interpretations separate from that imported evidence.
"""

PROCESSES = {
    "F01": {
        "short": "Establishment", "trigger": "An employer needs to enter the covered establishment ecosystem or change authorised representatives.",
        "path": "Registration evidence → office scrutiny → establishment decision → signatory and operator grants",
        "record": "Establishment registration, identifiers, jurisdiction and dated authorisations.",
        "control": "Distinguish the owner, preparer and signatory. Check who may act for which establishment and when a grant ends.",
        "exceptions": "Incomplete registration; verification failure; signatory revocation; change of jurisdiction.",
        "question": "Which source owns establishment identity, coverage status and signatory authority?", "sources": ["CMP", "SOP-B"],
        "services": ["employer-service", "platform-service"],
    },
    "F02": {
        "short": "Member identity", "trigger": "A worker joins, links employment or needs identity, KYC or profile corrections.",
        "path": "Employment link → member identity / KYC → verification → correction review → updated record",
        "record": "UAN, employment-specific member record, verified attributes and correction history.",
        "control": "Separate a person from an employment account. Corrections must preserve the old value, evidence and approving authority.",
        "exceptions": "Duplicate or mismatched identity; failed bank validation; pending employer attestation; disputed date of exit.",
        "question": "How are duplicates, identity mismatches and employer-independent corrections resolved?", "sources": ["JD", "WSU", "SOP-B"],
        "services": ["member-service", "employer-service", "workflow-service"],
    },
    "F03": {
        "short": "Contributions", "trigger": "The employer reports the contribution period and pays the associated liability.",
        "path": "Prepare ECR → validate → signatory approval → submit / TRRN → payment confirmation → ledger posting",
        "record": "Filing version, payment reference, balanced journal and member contribution statement.",
        "control": "Preparation and approval are different duties. Payment confirmation and member ledger posting are separate events; reconcile both.",
        "exceptions": "Validation errors; return to preparer; unpaid filing; bank failure; confirmed payment awaiting posting; supplementary corrections.",
        "question": "Can every payment be traced to one filing and exactly one balanced posting?", "sources": ["MAP", "CMP"],
        "services": ["contribution-service", "employer-service", "payment-simulator"],
    },
    "F04": {
        "short": "Claims & transfers", "trigger": "A member or beneficiary requests an advance, final settlement, transfer or death-related benefit.",
        "path": "Application → eligibility / risk checks → docket and scrutiny → authorised decision → payment → member outcome",
        "record": "Claim, approval round, decision evidence, payment instruction and ledger / notice outcome.",
        "control": "An approval is not proof of payment. Return for rework, final rejection and payment return are different business outcomes.",
        "exceptions": "Missing evidence; freeze / hold; return to initiator; rejection; payment return and bank correction; transfer-in or later credits.",
        "question": "Which evidence and rule version made the decision reproducible, and what remains outstanding after approval?", "sources": ["MAP", "EDLI", "SOP-B"],
        "services": ["claim-service", "workflow-service", "contribution-service", "payment-simulator"],
    },
    "F05": {
        "short": "Pension", "trigger": "A member or family seeks pension benefits, or a pensioner needs continuing disbursement services.",
        "path": "Application and service verification → pension decision / PPO → disbursement → life certificate and subsequent changes",
        "record": "Pension application, service / family evidence, PPO and continuing payment history.",
        "control": "Keep recurring pension (Form 10D) distinct from pension withdrawal benefit (Form 10C). A PF balance is not an EPS benefit calculation.",
        "exceptions": "Service gaps; family or nominee disputes; bank change; life certificate not recorded; revised entitlement.",
        "question": "Who owns pension entitlement, recurring payment reconciliation and survivor changes?", "sources": ["PEN", "MAP"],
        "services": ["pension-service", "member-service", "payment-simulator"],
    },
    "F06": {
        "short": "Compliance & recovery", "trigger": "A discrepancy, inspection or default needs scrutiny, proceedings, assessment or recovery.",
        "path": "Signal / inspection → case → notice and hearing → reasoned order / assessment → demand → payment or recovery / appeal",
        "record": "Case evidence, procedural notices, orders, demand references and recovery status.",
        "control": "Keep procedural due process and signed orders separate from a financial demand and its ledger. Notice, hearing, order, appeal and recovery contracts include planned scope.",
        "exceptions": "Contested facts; rescheduled hearing; appeal or stay; partial payment; corrected or superseded order.",
        "question": "Can an external proceedings portal send an accepted order without directly writing the financial ledger?", "sources": ["CMP", "ICF", "REC"],
        "services": ["compliance-service", "contribution-service", "workflow-service"],
    },
    "F07": {
        "short": "Freeze & vigilance", "trigger": "A risk signal or order restricts activity, followed by review and possible release.",
        "path": "Risk / request → freeze review and order → enforce hold → de-freeze decision → fresh scrutiny where required",
        "record": "Restriction scope, order, evidence, effective time and release history.",
        "control": "A hold changes what transactions may proceed. The POC models de-freeze as a fresh approval round where appropriate, not a silent continuation of stale approvals.",
        "exceptions": "Wrong account or scope; overlapping restrictions; payment already in progress; stale approvals after release.",
        "question": "Which services enforce an order, and how is complete enforcement proved?", "sources": ["FIA", "SOP-B"],
        "services": ["member-service", "employer-service", "claim-service", "workflow-service"],
    },
    "F08": {
        "short": "Grievances", "trigger": "A person raises a service issue and expects an accountable response.",
        "path": "Register → competent-office routing → assignment → response / escalation → resolution → feedback / reopening",
        "record": "Grievance, assigned office, correspondence, resolution and escalation history.",
        "control": "The grievance concerns a transaction but does not replace its underlying decision. Track ownership, elapsed time and evidence of resolution.",
        "exceptions": "Wrong office; unresolved response; escalation; reopening; a linked claim that is still pending.",
        "question": "Does closure mean a response was issued, or that the underlying member problem was resolved?", "sources": ["SOP-B", "OUL"],
        "services": ["grievance-service", "workflow-service", "platform-service"],
    },
    "F09": {
        "short": "Exempted trusts", "trigger": "An exempted establishment and its trust require returns, oversight and transfers.",
        "path": "Exemption / trust oversight → periodic returns → member-account reconciliation → inspection / transfer issues",
        "record": "Trust authorisation, returns, member account references and oversight findings.",
        "control": "Identify which institution holds the PF account and which scheme obligations remain with EPFO. Trust and EPFO records need reconciliation.",
        "exceptions": "Late returns; mismatched transfer records; deficiencies; surrender or cancellation of exemption.",
        "question": "Where does trust data become authoritative, and how are member transfers reconciled?", "sources": ["EXM", "CMP"],
        "services": ["compliance-service", "contribution-service", "member-service"],
    },
    "F10": {
        "short": "International workers", "trigger": "Cross-border employment requires classification and applicable social-security documentation.",
        "path": "Worker classification → supporting agreement / coverage evidence → certificate or contribution treatment → applicable benefit process",
        "record": "International-worker classification, relevant certificate and dated supporting evidence.",
        "control": "Country, agreement, coverage dates and worker classification matter. Do not infer legal eligibility from a demo persona or a synthetic rule.",
        "exceptions": "Expired or absent certificate; inconsistent worker classification; differing coverage periods; unresolved agreement applicability.",
        "question": "Who validates agreement applicability and preserves the dated documentary basis?", "sources": ["IWU", "CMP"],
        "services": ["international-service", "member-service", "contribution-service"],
    },
    "F11": {
        "short": "Inoperative accounts", "trigger": "An old or inactive account needs identification, reconciliation or a supported claim.",
        "path": "Locate account → establish identity / entitlement → reconcile historical records → authorised settlement or continued investigation",
        "record": "Historical member account, identity linkage, reconciliation and decision trail.",
        "control": "A match is a candidate, not proof of entitlement. Preserve historical identifiers and the evidence used to link them.",
        "exceptions": "Missing legacy records; multiple candidate matches; deceased member; disputed entitlement.",
        "question": "How are historical records searched without treating approximate identity matches as confirmed?", "sources": ["MAP", "SOP-B"],
        "services": ["member-service", "claim-service", "workflow-service"],
    },
    "F12": {
        "short": "Audit", "trigger": "An audit cycle or finding requires evidence, response and follow-up.",
        "path": "Audit scope → evidence / observations → management response → corrective action → verification and closure",
        "record": "Audit finding, cited evidence, accountable owner, action and closure basis.",
        "control": "A technical event log is not a complete business audit. Trace decisions, money and corrective action together.",
        "exceptions": "Unanswered finding; incomplete evidence; disputed observation; action recorded without verified closure.",
        "question": "Can an auditor reconstruct who acted, under what authority, with which evidence and financial effect?", "sources": ["AUD", "MAP"],
        "services": ["audit-service", "reporting-service", "platform-service"],
    },
    "F13": {
        "short": "Governance & reporting", "trigger": "Offices and oversight bodies need operational status, exceptions and public information.",
        "path": "Operational records → defined metrics / reports → regional and zonal review → headquarters / governance decisions",
        "record": "Report definition, source period, reconciliation basis and resulting action.",
        "control": "Distinguish counts of applications, decisions, successful payments and resolved issues. Preserve metric definitions and cut-off times.",
        "exceptions": "Late events; inconsistent totals; reporting lag; incorrect jurisdiction attribution.",
        "question": "Can a headline dashboard number be reconciled to individual business records?", "sources": ["EC", "OUL", "WEB"],
        "services": ["reporting-service", "intelligence-service", "platform-service"],
    },
    "F14": {
        "short": "Technology & security", "trigger": "People, systems and partners need access, operational support and change control.",
        "path": "Identity / staff posting → scoped authority → secure transaction → monitoring / incident response → review or revocation",
        "record": "Identity, effective assignment, entitlement, transaction audit and operational incident.",
        "control": "A staff posting, login identity and business authority are related but distinct records. Reassignment must invalidate stale access and case ownership.",
        "exceptions": "Officer transfer; expired delegation; stale projections; replayed callback; unavailable service; conflicting rule versions.",
        "question": "How quickly does a posting change revoke old access across every affected portal and service?", "sources": ["OUL", "REF"],
        "services": ["platform-service", "audit-service", "workflow-service", "mock-integrations"],
    },
}

REPLAYS = [
    {"scenario": "clm-settle-review", "title": "An advance reaches settlement", "lesson": "Follow one claim through member submission, DA scrutiny, AO approval, cash instruction, balance and notice. Approval and settlement are separate milestones.", "anchors": [3, 16, 21, 24]},
    {"scenario": "clm-pay-return-reissue", "title": "A returned payment is recovered", "lesson": "A failed bank check leaves the claim returned. A corrected account, APFC re-payment approval and cash reissue recover the payment without reopening entitlement.", "anchors": [23, 24, 29, 34]},
    {"scenario": "clm-return-resubmit", "title": "A checker returns a claim for rework", "lesson": "Return requires a reason and a fresh DA recommendation / docket before the AO decides again. Rework is not final rejection.", "anchors": [17, 19, 24, 31]},
    {"scenario": "clm-reject-apfc", "title": "A claim receives a reasoned rejection", "lesson": "DA recommendation passes through SS to APFC. The final rejection requires a reason and the observed PF balance remains unchanged.", "anchors": [10, 21, 22, 25]},
    {"scenario": "clm-settle-f19", "title": "Final PF settlement: gross, tax and net", "lesson": "The recorded Form 19 case takes the DA → AO → OIC route. Gross ₹30,00,000, simulated TDS ₹3,00,000 and net ₹27,00,000 demonstrate why bank amount and PF debit must be distinguished. This is illustrative policy, not a statutory tax calculation.", "anchors": [3, 21, 26, 29], "expected_fields": {"gross_paise": 300000000, "tds_paise": 30000000, "net_paise": 270000000}},
    {"scenario": "clm-settle-10c", "title": "EPS withdrawal is separate from PF", "lesson": "The recorded Form 10C benefit is ₹46,500 under the illustrative Table D simulation. It settles through DA → SS → cash while the observed PF balance stays unchanged. This is not a recurring Form 10D pension replay.", "anchors": [3, 16, 21, 24], "expected_fields": {"amount_paise": 4650000}},
]

# Repository source register: content accessibility was not independently confirmed
# during handbook creation. Dates in titles are dates recorded by the repository.
SOURCES = {
    "MAP": ("Manual of Accounting Procedure, Part I", "https://pmvbry.epfindia.gov.in/wp-content/uploads/2025/11/MAP_PartI_Complete.pdf"),
    "AUD": ("Audit Manual (repository date: 8 December 2023)", "https://pmvbry.epfindia.gov.in/wp-content/uploads/2025/11/Audit_Manual_08122023.pdf"),
    "CMP": ("Compliance Manual (repository date: 5 February 2024)", "https://pmvbry.epfindia.gov.in/wp-content/uploads/2025/11/ComplianceManual.pdf"),
    "REC": ("Recovery Manual (repository date: 8 December 2023)", "https://pmvbry.epfindia.gov.in/wp-content/uploads/2025/11/Recovery_Manual_08122023.pdf"),
    "EXM": ("Exemption Manual (repository date: 8 December 2023)", "https://pmvbry.epfindia.gov.in/wp-content/uploads/2025/11/Exemption_Manual_08122023.pdf"),
    "PEN": ("Pension Manual", "https://pmvbry.epfindia.gov.in/wp-content/uploads/2025/11/Pension_Manual.pdf"),
    "EDLI": ("EDLI Manual", "https://pmvbry.epfindia.gov.in/wp-content/uploads/2025/11/EDLI_Manual.pdf"),
    "SOP-B": ("Part B: SOPs and service standards", "https://pmvbry.epfindia.gov.in/wp-content/uploads/2025/11/PARTB_SOP_AND_STs_1.pdf"),
    "ICF": ("Inspector-cum-Facilitator manual", "https://pmvbry-cdn.epfindia.gov.in/wp-content/uploads/2025/08/Manual_for_Inspector_cum_Facilitator.pdf"),
    "EC": ("Executive Committee meeting agenda (98th)", "https://pmvbry.epfindia.gov.in/wp-content/uploads/2025/12/EC_meeting_Agenda_98th.pdf"),
    "JD": ("Joint declaration SOP circular (repository date: 1 August 2024)", "https://pmvbry.epfindia.gov.in/wp-content/uploads/2025/09/Circular_WSU_01082024-1.pdf"),
    "WSU": ("WSU SOP circular (repository date: 2 August 2024)", "https://pmvbry.epfindia.gov.in/wp-content/uploads/2025/09/Circular_SOP_WSU_02082024-5.pdf"),
    "IWU": ("International workers: online Certificate of Coverage circular", "https://epfindia.gov.in/site_docs/PDFs/Circulars/Y2017-2018/IWU_OnlineSystem_COC_10677.pdf"),
    "OUL": ("Office-use portal catalogue", "https://pmvbry.epfindia.gov.in/for_office_use/logins-of-office-use/"),
    "REF": ("EPFO reforms: repository reference dated 12 February 2026", "https://pmvbry-cdn.epfindia.gov.in/wp-content/uploads/2026/03/EPFO-REFORMS-Posted-On-12-Feb-2026.pdf"),
    "FIA": ("Freeze / de-freeze SOP reference", None),
    "WEB": ("Public information references in the repository", None),
    "UAN": ("Official UAN FAQ for members; search-index reference, direct retrieval unsuccessful", "https://epfindia.gov.in/site_docs/PDFs/UAN_PDFs/UAN_ForMembers/FAQ-Member-Ver1.1.pdf"),
    "SCHEMES": ("Official EPFO newsletter, October–December 2024; search-index reference, direct retrieval unsuccessful", "https://www.epfindia.gov.in/site_docs/PDFs/Updates/Newsletter_October_Dec_2024_EPFO.pdf"),
    "FRM": ("Fraud risk mitigation success story; archived repository reference", "https://epfindia.gov.in/site_docs/PDFs/Updates/Success_Story_EPFO.pdf"),
    "SS": ("Samadhan Setu issue-tracker extract, 24 September 2026, in ../samadhan-setu files/. Module names / error text are primary issue evidence; explanatory narratives are secondary", None),
    "EP": ("Activity source code EP: authority pointer unresolved in the repository source register; requires domain confirmation", None),
    "PD": ("Activity source code PD: authority pointer unresolved in the repository source register; requires domain confirmation", None),
}

GLOSSARY = [
    ("EPFO", "Employees’ Provident Fund Organisation", "The institution around which this prototype models member, employer and office processes."),
    ("EPF", "Employees’ Provident Fund", "Provident-fund account and benefit context; keep the balance and ledger distinct from pension calculations."),
    ("EPS", "Employees’ Pension Scheme", "Pension context, including recurring pension and eligible withdrawal benefits; this handbook does not determine eligibility."),
    ("EDLI", "Employees’ Deposit Linked Insurance", "Death-related insurance benefit context; distinguish it from PF balance settlement and family pension."),
    ("UAN", "Universal Account Number", "Person-level umbrella identifier used to link employment-specific member IDs. A login, a UAN and a ledger account are different objects."),
    ("Member ID", "Employment-specific member identifier", "Identifies a member’s employment-linked record; a person may have records across employers."),
    ("ECR", "Electronic Challan-cum-Return", "Employer contribution filing; preparation, approval, payment and posting are separate steps."),
    ("TRRN", "Temporary Return Reference Number", "Filing / challan reference used in the payment journey; it is not proof that the member ledger was posted."),
    ("KYC", "Know Your Customer", "Identity and account verification evidence; simulated verification in the POC is labelled as mock."),
    ("DA", "Dealing Assistant", "Initiating office scrutiny role. The exact authority depends on the process and effective delegation."),
    ("SS", "Section Supervisor", "An office supervisory role used in several illustrative approval chains."),
    ("AO", "Accounts Officer", "Office accounts role; one of the checker roles shown in the recorded claims."),
    ("APFC", "Assistant Provident Fund Commissioner", "Office authority represented in claim decisions and re-payment approval in the POC."),
    ("OIC", "Officer in Charge", "Office authority represented in the larger illustrative settlement chain."),
    ("CAD", "Claim Approval Docket", "POC decision packet: evidence and calculations inspected before recommendation or decision. It is not a digitally signed official order."),
    ("PPO", "Pension Payment Order", "Pension award / payment reference; distinct from a one-time claim reference."),
    ("Form 19", "Final PF settlement", "Benefit context shown in a recorded synthetic settlement; exact real eligibility must come from current applicable sources."),
    ("Form 10C", "Pension withdrawal benefit / scheme-certificate context", "The replay shows a synthetic withdrawal benefit, not every Form 10C option."),
    ("Form 10D", "Pension application", "Recurring pension / family-pension application context; no recorded Form 10D replay is embedded."),
    ("Form 13", "Transfer request", "Employment mobility context: reconcile service and balance movement across member records."),
    ("TDS", "Tax Deducted at Source", "The example deduction is generated by illustrative demo rules; do not use it to determine actual tax."),
    ("RO / ZO / HO", "Regional / Zonal / Head Office", "Office levels used in the repository’s jurisdiction and escalation model, not a verified current organisational directory."),
    ("CBT", "Central Board of Trustees", "Governance context; the operational office roles and oversight bodies serve different purposes."),
    ("CoC", "Certificate of Coverage", "International-worker coverage evidence; agreement and date applicability need domain validation."),
    ("Ledger", "Financial journal and account records", "In this POC, contribution-service owns balanced postings in integer paise; services must not write another service’s ledger tables."),
    ("Idempotency", "Safe repetition of one business instruction", "The same accepted command or event should not create a second payment or posting."),
    ("Maker / checker", "Separate preparation and approval duties", "A distinct authorised person reviews the initiating action; a role label alone does not prove separation of people."),
    ("Posting", "Financial or staff context", "A ledger posting records money. An HR posting assigns an officer to a role / office. Always specify which meaning is intended."),
]
