"""GENERATED by packages/service-template/scaffold.py from docs/endpoint-catalogue.md — do not edit.

Phase-1 operations owned by this service. Until an operation is implemented, it verifies the caller's
internal token and answers 501 /problems/not-yet-built. Replace a stub by adding a real route with the
same method and path in app/api/routes.py; stubs are only registered for paths not already routed."""
from fastapi import APIRouter, Depends

from epfo_auth import Actor, require_actor
from epfo_observability import Problem

router = APIRouter()

OPERATIONS = ['GET /public/defaulting-establishments', 'GET /employers/me/vishwas-applications', 'POST /employers/me/vishwas-applications', 'GET /office/compliance/cases', 'POST /office/compliance/cases', 'GET /office/compliance/vishwas-applications', 'GET /office/compliance/cases/{caseId}', 'POST /office/compliance/vishwas-applications/{applicationId}/decisions']

@router.api_route("/api/v1/public/defaulting-establishments", methods=["GET"], include_in_schema=False)
async def get_public_defaulting_establishments(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Published defaulter list (synthetic)")


@router.api_route("/api/v1/employers/me/vishwas-applications", methods=["GET"], include_in_schema=False)
async def get_employers_me_vishwas_applications(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "The establishment's VISHWAS applications and its open 14B demands")


@router.api_route("/api/v1/employers/me/vishwas-applications", methods=["POST"], include_in_schema=False)
async def post_employers_me_vishwas_applications(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Apply under VISHWAS (one-time settlement of 14B damages / penalty disputes at reduced rates for past")


@router.api_route("/api/v1/office/compliance/cases", methods=["GET"], include_in_schema=False)
async def get_office_compliance_cases(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Case search")


@router.api_route("/api/v1/office/compliance/cases", methods=["POST"], include_in_schema=False)
async def post_office_compliance_cases(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Open proceeding / enforcement case")


@router.api_route("/api/v1/office/compliance/vishwas-applications", methods=["GET"], include_in_schema=False)
async def get_office_compliance_vishwas_applications(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "VISHWAS applications of the office's establishments")


@router.api_route("/api/v1/office/compliance/cases/{caseId}", methods=["GET"], include_in_schema=False)
async def get_office_compliance_cases_caseId(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Case detail with full proceeding history")


@router.api_route("/api/v1/office/compliance/vishwas-applications/{applicationId}/decisions", methods=["POST"], include_in_schema=False)
async def post_office_compliance_vishwas_applications_applicationId_decisions(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Recalculate damages under VISHWAS and decide the application → DemandRaised.v1 for the revised amoun")
