"""GENERATED by packages/service-template/scaffold.py from docs/endpoint-catalogue.md — do not edit.

Phase-1 operations owned by this service. Until an operation is implemented, it verifies the caller's
internal token and answers 501 /problems/not-yet-built. Replace a stub by adding a real route with the
same method and path in app/api/routes.py; stubs are only registered for paths not already routed."""
from fastapi import APIRouter, Depends

from epfo_auth import Actor, require_actor
from epfo_observability import Problem

router = APIRouter()

OPERATIONS = ['GET /employers/me', 'PATCH /employers/me', 'POST /employers/registration-requests', 'GET /office/establishment-change-requests', 'GET /office/establishment-registrations', 'GET /public/establishments', 'GET /employers/me/bank-accounts', 'GET /employers/me/branches', 'POST /employers/me/branches', 'GET /employers/me/change-requests', 'GET /employers/me/configuration', 'GET /employers/me/contractors', 'POST /employers/me/contractors', 'GET /employers/me/exemption', 'GET /employers/me/kyc', 'GET /employers/me/operators', 'GET /employers/me/ownership-declaration', 'PUT /employers/me/ownership-declaration', 'GET /employers/me/signatories', 'POST /employers/me/configuration/change-requests', 'POST /employers/me/operators/invitations', 'POST /employers/me/signatories/authorisations', 'POST /employers/me/kyc/{kycType}', 'POST /employers/me/operators/{operatorId}/revocations', 'POST /employers/me/signatories/{signatoryId}/revocations', 'GET /employers/registration-requests/{reqId}', 'GET /public/establishments/{estId}', 'POST /employers/registration-requests/{reqId}/verification-evidence', 'POST /office/establishment-registrations/{reqId}/coverage-decisions', 'GET /office/establishment-registrations/{reqId}/documents', 'POST /office/establishment-registrations/{reqId}/scrutiny-notes', 'POST /office/establishments/{estId}/defreezes', 'POST /office/establishments/{estId}/freezes', 'POST /office/establishments/{estId}/change-requests/{requestId}/decisions']

@router.api_route("/api/v1/employers/me", methods=["GET"], include_in_schema=False)
async def get_employers_me(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Establishment profile (active establishment chosen via X-Establishment-Id, validated server-side)")


@router.api_route("/api/v1/employers/me", methods=["PATCH"], include_in_schema=False)
async def patch_employers_me(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Update address / contact — creates a change request, not a direct edit")


@router.api_route("/api/v1/employers/registration-requests", methods=["POST"], include_in_schema=False)
async def post_employers_registration_requests(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "New establishment registration request")


@router.api_route("/api/v1/office/establishment-change-requests", methods=["GET"], include_in_schema=False)
async def get_office_establishment_change_requests(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Establishment change requests of the office, by state")


@router.api_route("/api/v1/office/establishment-registrations", methods=["GET"], include_in_schema=False)
async def get_office_establishment_registrations(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "OLRE: new registrations of the office awaiting scrutiny / coverage")


@router.api_route("/api/v1/public/establishments", methods=["GET"], include_in_schema=False)
async def get_public_establishments(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Establishment search by code, registration, pincode, name or industry; filter by location, type, exe")


@router.api_route("/api/v1/employers/me/bank-accounts", methods=["GET"], include_in_schema=False)
async def get_employers_me_bank_accounts(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Establishment bank accounts used for remittance")


@router.api_route("/api/v1/employers/me/branches", methods=["GET"], include_in_schema=False)
async def get_employers_me_branches(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Sub-codes / branches / departments")


@router.api_route("/api/v1/employers/me/branches", methods=["POST"], include_in_schema=False)
async def post_employers_me_branches(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Create sub-code")


@router.api_route("/api/v1/employers/me/change-requests", methods=["GET"], include_in_schema=False)
async def get_employers_me_change_requests(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "The establishment's change requests and the office's decisions")


@router.api_route("/api/v1/employers/me/configuration", methods=["GET"], include_in_schema=False)
async def get_employers_me_configuration(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Establishment configuration (read-only, seeded): coverage date, exemption status, coverage type, jur")


@router.api_route("/api/v1/employers/me/contractors", methods=["GET"], include_in_schema=False)
async def get_employers_me_contractors(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Principal employer: linked contractors")


@router.api_route("/api/v1/employers/me/contractors", methods=["POST"], include_in_schema=False)
async def post_employers_me_contractors(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Principal employer: register / link contractor")


@router.api_route("/api/v1/employers/me/exemption", methods=["GET"], include_in_schema=False)
async def get_employers_me_exemption(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Exemption details (PF trust, relaxation)")


@router.api_route("/api/v1/employers/me/kyc", methods=["GET"], include_in_schema=False)
async def get_employers_me_kyc(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Establishment KYC status: PAN, TAN, GSTIN, CIN, LIN")


@router.api_route("/api/v1/employers/me/operators", methods=["GET"], include_in_schema=False)
async def get_employers_me_operators(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "List operators")


@router.api_route("/api/v1/employers/me/ownership-declaration", methods=["GET"], include_in_schema=False)
async def get_employers_me_ownership_declaration(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Form 5A ownership / management declaration — view")


@router.api_route("/api/v1/employers/me/ownership-declaration", methods=["PUT"], include_in_schema=False)
async def put_employers_me_ownership_declaration(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Form 5A — submit / amend")


@router.api_route("/api/v1/employers/me/signatories", methods=["GET"], include_in_schema=False)
async def get_employers_me_signatories(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "List authorised signatories")


@router.api_route("/api/v1/employers/me/configuration/change-requests", methods=["POST"], include_in_schema=False)
async def post_employers_me_configuration_change_requests(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Request configuration change (office-approved)")


@router.api_route("/api/v1/employers/me/operators/invitations", methods=["POST"], include_in_schema=False)
async def post_employers_me_operators_invitations(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Invite operator with scoped permissions (a privileged grant)")


@router.api_route("/api/v1/employers/me/signatories/authorisations", methods=["POST"], include_in_schema=False)
async def post_employers_me_signatories_authorisations(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Authorise signatory")


@router.api_route("/api/v1/employers/me/kyc/{kycType}", methods=["POST"], include_in_schema=False)
async def post_employers_me_kyc_kycType(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Seed / update establishment KYC (mock registry verification)")


@router.api_route("/api/v1/employers/me/operators/{operatorId}/revocations", methods=["POST"], include_in_schema=False)
async def post_employers_me_operators_operatorId_revocations(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Revoke operator (Journey A9)")


@router.api_route("/api/v1/employers/me/signatories/{signatoryId}/revocations", methods=["POST"], include_in_schema=False)
async def post_employers_me_signatories_signatoryId_revocations(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Revoke / replace signatory (Journey D5)")


@router.api_route("/api/v1/employers/registration-requests/{reqId}", methods=["GET"], include_in_schema=False)
async def get_employers_registration_requests_reqId(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Registration status")


@router.api_route("/api/v1/public/establishments/{estId}", methods=["GET"], include_in_schema=False)
async def get_public_establishments_estId(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Public profile: name, registration, office, location, type, industry, coverage, verification and exe")


@router.api_route("/api/v1/employers/registration-requests/{reqId}/verification-evidence", methods=["POST"], include_in_schema=False)
async def post_employers_registration_requests_reqId_verification_evidence(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Submit demo verification evidence (PAN/CIN/GSTIN/LIN) to mock registry adapter (Journey A1)")


@router.api_route("/api/v1/office/establishment-registrations/{reqId}/coverage-decisions", methods=["POST"], include_in_schema=False)
async def post_office_establishment_registrations_reqId_coverage_decisions(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Circle officer's coverage decision on a new establishment")


@router.api_route("/api/v1/office/establishment-registrations/{reqId}/documents", methods=["GET"], include_in_schema=False)
async def get_office_establishment_registrations_reqId_documents(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "DA (Compliance) views documents of a new registration (FO-interface >> OLRE >> View Documents)")


@router.api_route("/api/v1/office/establishment-registrations/{reqId}/scrutiny-notes", methods=["POST"], include_in_schema=False)
async def post_office_establishment_registrations_reqId_scrutiny_notes(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "DA (Compliance) records scrutiny and opens the compliance e-file")


@router.api_route("/api/v1/office/establishments/{estId}/defreezes", methods=["POST"], include_in_schema=False)
async def post_office_establishments_estId_defreezes(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "De-freeze an establishment, maker-checker")


@router.api_route("/api/v1/office/establishments/{estId}/freezes", methods=["POST"], include_in_schema=False)
async def post_office_establishments_estId_freezes(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Freeze an establishment")


@router.api_route("/api/v1/office/establishments/{estId}/change-requests/{requestId}/decisions", methods=["POST"], include_in_schema=False)
async def post_office_establishments_estId_change_requests_requestId_decisions(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Decide configuration change / closure / office-transfer requests")
