"""GENERATED by packages/service-template/scaffold.py from docs/endpoint-catalogue.md — do not edit.

Phase-1 operations owned by this service. Until an operation is implemented, it verifies the caller's
internal token and answers 501 /problems/not-yet-built. Replace a stub by adding a real route with the
same method and path in app/api/routes.py; stubs are only registered for paths not already routed."""
from fastapi import APIRouter, Depends

from epfo_auth import Actor, require_actor
from epfo_observability import Problem

router = APIRouter()

OPERATIONS = ['GET /employers/me', 'POST /employers/registration-requests', 'GET /public/establishments', 'GET /employers/me/configuration', 'GET /employers/me/operators', 'GET /employers/me/signatories', 'POST /employers/me/operators/invitations', 'POST /employers/me/signatories/authorisations', 'POST /employers/me/operators/{operatorId}/revocations', 'POST /employers/me/signatories/{signatoryId}/revocations', 'GET /employers/registration-requests/{reqId}', 'GET /public/establishments/{estId}', 'POST /employers/registration-requests/{reqId}/verification-evidence']

@router.api_route("/api/v1/employers/me", methods=["GET"], include_in_schema=False)
async def get_employers_me(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Establishment profile (active establishment chosen via X-Establishment-Id, validated server-side)")


@router.api_route("/api/v1/employers/registration-requests", methods=["POST"], include_in_schema=False)
async def post_employers_registration_requests(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "New establishment registration request")


@router.api_route("/api/v1/public/establishments", methods=["GET"], include_in_schema=False)
async def get_public_establishments(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Establishment search by code, registration, pincode, name or industry; filter by location, type, exe")


@router.api_route("/api/v1/employers/me/configuration", methods=["GET"], include_in_schema=False)
async def get_employers_me_configuration(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Establishment configuration (read-only, seeded): coverage date, exemption status, coverage type, jur")


@router.api_route("/api/v1/employers/me/operators", methods=["GET"], include_in_schema=False)
async def get_employers_me_operators(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "List operators")


@router.api_route("/api/v1/employers/me/signatories", methods=["GET"], include_in_schema=False)
async def get_employers_me_signatories(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "List authorised signatories")


@router.api_route("/api/v1/employers/me/operators/invitations", methods=["POST"], include_in_schema=False)
async def post_employers_me_operators_invitations(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Invite operator with scoped permissions (a privileged grant)")


@router.api_route("/api/v1/employers/me/signatories/authorisations", methods=["POST"], include_in_schema=False)
async def post_employers_me_signatories_authorisations(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Authorise signatory")


@router.api_route("/api/v1/employers/me/operators/{operatorId}/revocations", methods=["POST"], include_in_schema=False)
async def post_employers_me_operators_operatorId_revocations(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Revoke operator (Journey A9)")


@router.api_route("/api/v1/employers/me/signatories/{signatoryId}/revocations", methods=["POST"], include_in_schema=False)
async def post_employers_me_signatories_signatoryId_revocations(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Revoke / replace signatory (Journey D5)")


@router.api_route("/api/v1/employers/registration-requests/{reqId}", methods=["GET"], include_in_schema=False)
async def get_employers_registration_requests_reqId(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Registration status")


@router.api_route("/api/v1/public/establishments/{estId}", methods=["GET"], include_in_schema=False)
async def get_public_establishments_estId(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Public profile: name, registration, office, location, type, industry, coverage, verification and exe")


@router.api_route("/api/v1/employers/registration-requests/{reqId}/verification-evidence", methods=["POST"], include_in_schema=False)
async def post_employers_registration_requests_reqId_verification_evidence(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Submit demo verification evidence (PAN/CIN/GSTIN/LIN) to mock registry adapter (Journey A1)")
