#!/usr/bin/env python3
"""Scaffold (or refresh) EPFO POC services from one template so every service has the same shape.

    python3 packages/service-template/scaffold.py            # all services
    python3 packages/service-template/scaffold.py claim-service

Creates services/<name>/ from packages/service-template/template/ (only files that do not exist yet,
so hand-written code is never overwritten), and ALWAYS regenerates
services/<name>/app/api/catalogue_routes.py from docs/endpoint-catalogue.md.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TEMPLATE = Path(__file__).with_name("template")
sys.path.insert(0, str(ROOT / "docs" / "tools"))
from build_gate0 import load_catalogue  # noqa: E402

# service directory -> catalogue owner (None = no public API of its own)
SERVICES = {
    "employer-service": "employer",
    "member-service": "member",
    "contribution-service": "contribution",
    "claim-service": "claim",
    "payment-simulator": "payment-simulator",
    "workflow-service": "workflow",
    "grievance-service": "grievance",
    "audit-service": "audit",
    "reporting-service": "reporting",
    "intelligence-service": "intelligence",
    "pension-service": "pension",
    "platform-service": "platform",
    "mock-integrations": None,
}
PHASE_1_BUILT = {"W", "M"}  # status values that are in scope for this POC phase


def fastapi_path(path: str) -> str:
    return path  # catalogue templates already use {param} syntax


def func_name(method: str, path: str) -> str:
    parts = [p.strip("{}").replace("-", "_") for p in path.strip("/").split("/") if p]
    return f"{method.lower()}_" + "_".join(parts)


def catalogue_routes(owner: str | None) -> str:
    ops = [op for op in load_catalogue().values()
           if owner and op["owner"] == owner and op["status"] in PHASE_1_BUILT and op["phase"] == 1]
    # FastAPI matches in registration order: literal segments must beat {templated} ones.
    ops.sort(key=lambda op: ([1 if seg.startswith("{") else 0 for seg in op["path"].split("/")], op["path"], op["method"]))
    lines = [
        '"""GENERATED by packages/service-template/scaffold.py from docs/endpoint-catalogue.md — do not edit.',
        "",
        "Phase-1 operations owned by this service. Until an operation is implemented, it verifies the caller's",
        "internal token and answers 501 /problems/not-yet-built. Replace a stub by adding a real route with the",
        'same method and path in app/api/routes.py; stubs are only registered for paths not already routed."""',
        "from fastapi import APIRouter, Depends",
        "",
        "from epfo_auth import Actor, require_actor",
        "from epfo_observability import Problem",
        "",
        "router = APIRouter()",
        "",
        f"OPERATIONS = {[f'{op["method"]} {op["path"]}' for op in ops]!r}",
        "",
    ]
    seen = set()
    for op in ops:
        name = func_name(op["method"], op["path"])
        if name in seen:
            continue
        seen.add(name)
        summary = op["summary"].replace('"', "'")[:100]
        lines += [
            f'@router.api_route("/api/v1{fastapi_path(op["path"])}", methods=["{op["method"]}"], include_in_schema=False)',
            f"async def {name}(actor: Actor = Depends(require_actor)) -> None:",
            f'    raise Problem(501, "/problems/not-yet-built", "Not built yet", "{summary}")',
            "",
            "",
        ]
    return "\n".join(lines).rstrip() + "\n"


def scaffold(name: str) -> list[str]:
    target = ROOT / "services" / name
    created = []
    subs = {"{{SERVICE_NAME}}": name, "{{SERVICE_MODULE}}": name.replace("-", "_"),
            "{{DB_NAME}}": name.replace("-service", "").replace("-", "_") + "_db"}
    for src in sorted(TEMPLATE.rglob("*")):
        if src.is_dir() or "__pycache__" in src.parts:
            continue
        dest = target / src.relative_to(TEMPLATE)
        if dest.name.endswith(".tmpl"):
            dest = dest.with_name(dest.name[:-5])
        if dest.exists():
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        text = src.read_text(encoding="utf-8")
        for k, v in subs.items():
            text = text.replace(k, v)
        dest.write_text(text, encoding="utf-8")
        created.append(str(dest.relative_to(ROOT)))
    routes = target / "app" / "api" / "catalogue_routes.py"
    routes.write_text(catalogue_routes(SERVICES[name]), encoding="utf-8")
    return created


def main() -> None:
    names = sys.argv[1:] or list(SERVICES)
    for name in names:
        if name not in SERVICES:
            raise SystemExit(f"unknown service {name}; known: {', '.join(SERVICES)}")
        created = scaffold(name)
        ops = len(load_catalogue()) and catalogue_routes(SERVICES[name]).count("@router.api_route")
        print(f"{name}: {len(created)} files created, {ops} phase-1 operations routed")


if __name__ == "__main__":
    main()
