"""GENERATED by packages/service-template/scaffold.py from docs/endpoint-catalogue.md — do not edit.

Phase-1 operations owned by this service. Until an operation is implemented, it verifies the caller's
internal token and answers 501 /problems/not-yet-built. Replace a stub by adding a real route with the
same method and path in app/api/routes.py; stubs are only registered for paths not already routed."""
from fastapi import APIRouter, Depends

from epfo_auth import Actor, require_actor
from epfo_observability import Problem

router = APIRouter()

OPERATIONS = ['GET /ndc/event-failures', 'GET /ndc/health', 'POST /ndc/event-failures/{eventId}/replays']

@router.api_route("/api/v1/ndc/event-failures", methods=["GET"], include_in_schema=False)
async def get_ndc_event_failures(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Failed events / DLQ view (interface 11)")


@router.api_route("/api/v1/ndc/health", methods=["GET"], include_in_schema=False)
async def get_ndc_health(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Platform endpoint defined in init.md §3.1")


@router.api_route("/api/v1/ndc/event-failures/{eventId}/replays", methods=["POST"], include_in_schema=False)
async def post_ndc_event_failures_eventId_replays(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Replay a dead-lettered event (idempotent consumers)")
