"""GENERATED by packages/service-template/scaffold.py from docs/endpoint-catalogue.md — do not edit.

Phase-1 operations owned by this service. Until an operation is implemented, it verifies the caller's
internal token and answers 501 /problems/not-yet-built. Replace a stub by adding a real route with the
same method and path in app/api/routes.py; stubs are only registered for paths not already routed."""
from fastapi import APIRouter, Depends

from epfo_auth import Actor, require_actor
from epfo_observability import Problem

router = APIRouter()

OPERATIONS = ['GET /ndc/event-failures', 'GET /ndc/health', 'POST /training/sandboxes', 'GET /ho/config/rule-sets', 'POST /ho/config/rule-sets', 'POST /ndc/dr/failover-drills', 'GET /ndc/dr/replication-status', 'GET /ndc/issue-tracker/requests', 'POST /ndc/issue-tracker/requests', 'GET /public/policy/current', 'GET /ho/config/rule-sets/{versionId}', 'PUT /ho/config/rule-sets/{versionId}', 'POST /ho/config/rule-sets/{versionId}/decisions', 'POST /ho/config/rule-sets/{versionId}/submissions', 'POST /ndc/issue-tracker/requests/{requestId}/executions', 'POST /ndc/event-failures/{eventId}/replays']

@router.api_route("/api/v1/ndc/event-failures", methods=["GET"], include_in_schema=False)
async def get_ndc_event_failures(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Failed events / DLQ view (interface 11)")


@router.api_route("/api/v1/ndc/health", methods=["GET"], include_in_schema=False)
async def get_ndc_health(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Platform endpoint defined in init.md §3.1")


@router.api_route("/api/v1/training/sandboxes", methods=["POST"], include_in_schema=False)
async def post_training_sandboxes(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Create a synthetic-data training sandbox (PDNASA / ZTI)")


@router.api_route("/api/v1/ho/config/rule-sets", methods=["GET"], include_in_schema=False)
async def get_ho_config_rule_sets(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Policy administration: rule-set versions in force, scheduled, drafts and history")


@router.api_route("/api/v1/ho/config/rule-sets", methods=["POST"], include_in_schema=False)
async def post_ho_config_rule_sets(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Draft a new rule-set version (wage ceilings, rates, claim types, approval matrix, auto-settlement, g")


@router.api_route("/api/v1/ndc/dr/failover-drills", methods=["POST"], include_in_schema=False)
async def post_ndc_dr_failover_drills(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Run a DR failover drill")


@router.api_route("/api/v1/ndc/dr/replication-status", methods=["GET"], include_in_schema=False)
async def get_ndc_dr_replication_status(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "ADC (DR site) replication status")


@router.api_route("/api/v1/ndc/issue-tracker/requests", methods=["GET"], include_in_schema=False)
async def get_ndc_issue_tracker_requests(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Issue Tracker requests: all (IS Division) or the officer's own")


@router.api_route("/api/v1/ndc/issue-tracker/requests", methods=["POST"], include_in_schema=False)
async def post_ndc_issue_tracker_requests(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Raise an Issue Tracker request (e.g. freeze / de-freeze), with the order attached")


@router.api_route("/api/v1/public/policy/current", methods=["GET"], include_in_schema=False)
async def get_public_policy_current(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "The rule set in force today: ceilings, rates, claim types and limits (public figures only)")


@router.api_route("/api/v1/ho/config/rule-sets/{versionId}", methods=["GET"], include_in_schema=False)
async def get_ho_config_rule_sets_versionId(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "One rule set: its checks, what changed from its base, and worked examples of the effect")


@router.api_route("/api/v1/ho/config/rule-sets/{versionId}", methods=["PUT"], include_in_schema=False)
async def put_ho_config_rule_sets_versionId(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Edit a draft (If-Match)")


@router.api_route("/api/v1/ho/config/rule-sets/{versionId}/decisions", methods=["POST"], include_in_schema=False)
async def post_ho_config_rule_sets_versionId_decisions(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Approve and publish (effective from its date), or return, a submitted rule set; approver ≠ drafter")


@router.api_route("/api/v1/ho/config/rule-sets/{versionId}/submissions", methods=["POST"], include_in_schema=False)
async def post_ho_config_rule_sets_versionId_submissions(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Submit a draft that passes every check for approval")


@router.api_route("/api/v1/ndc/issue-tracker/requests/{requestId}/executions", methods=["POST"], include_in_schema=False)
async def post_ndc_issue_tracker_requests_requestId_executions(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "IS Division executes the block / unblock")


@router.api_route("/api/v1/ndc/event-failures/{eventId}/replays", methods=["POST"], include_in_schema=False)
async def post_ndc_event_failures_eventId_replays(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Replay a dead-lettered event (idempotent consumers)")
