"""GENERATED by packages/service-template/scaffold.py from docs/endpoint-catalogue.md — do not edit.

Phase-1 operations owned by this service. Until an operation is implemented, it verifies the caller's
internal token and answers 501 /problems/not-yet-built. Replace a stub by adding a real route with the
same method and path in app/api/routes.py; stubs are only registered for paths not already routed."""
from fastapi import APIRouter, Depends

from epfo_auth import Actor, require_actor
from epfo_observability import Problem

router = APIRouter()

OPERATIONS = ['POST /ai/feedback', 'GET /ai/models', 'GET /caiu/synthetic-risk-signals', 'POST /ho/circulars', 'GET /public/circulars', 'POST /ai/claims/analyse', 'POST /ai/grievances/classify', 'POST /ai/knowledge/search', 'POST /caiu/synthetic-risk-signals/{signalId}/reviews']

@router.api_route("/api/v1/ai/feedback", methods=["POST"], include_in_schema=False)
async def post_ai_feedback(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Platform endpoint defined in init.md §3.1")


@router.api_route("/api/v1/ai/models", methods=["GET"], include_in_schema=False)
async def get_ai_models(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Platform endpoint defined in init.md §3.1")


@router.api_route("/api/v1/caiu/synthetic-risk-signals", methods=["GET"], include_in_schema=False)
async def get_caiu_synthetic_risk_signals(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "CAIU risk signals (Journey D2)")


@router.api_route("/api/v1/ho/circulars", methods=["POST"], include_in_schema=False)
async def post_ho_circulars(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Publish a circular to the public corpus")


@router.api_route("/api/v1/public/circulars", methods=["GET"], include_in_schema=False)
async def get_public_circulars(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Circulars / notifications catalogue (synthetic, versioned documents)")


@router.api_route("/api/v1/ai/claims/analyse", methods=["POST"], include_in_schema=False)
async def post_ai_claims_analyse(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Platform endpoint defined in init.md §3.1")


@router.api_route("/api/v1/ai/grievances/classify", methods=["POST"], include_in_schema=False)
async def post_ai_grievances_classify(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Platform endpoint defined in init.md §3.1")


@router.api_route("/api/v1/ai/knowledge/search", methods=["POST"], include_in_schema=False)
async def post_ai_knowledge_search(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Platform endpoint defined in init.md §3.1")


@router.api_route("/api/v1/caiu/synthetic-risk-signals/{signalId}/reviews", methods=["POST"], include_in_schema=False)
async def post_caiu_synthetic_risk_signals_signalId_reviews(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Investigator disposition (Journey D4)")
