#!/usr/bin/env python3
"""Generate the Gate 0 design-freeze package (init.md §10, Gate 0).

Inputs (by hand):  docs/endpoint-catalogue.md, docs/stakeholders.md, docs/stakeholder-activities.yaml
Outputs (generated, do not edit by hand):
  docs/permissions.md          readable permission matrix, separation of duties, must-deny tests
  docs/permissions.yaml        machine-readable matrix (stakeholder -> endpoint -> scope)
  docs/api-matrix.md           21 interfaces -> stakeholders -> endpoints -> Working / Mock / Planned
  contracts/openapi/<service>.yaml   OpenAPI 3.1 skeleton per owning service
  contracts/openapi/gateway.yaml     consolidated gateway specification
  contracts/events/<Event>.schema.json   JSON Schema (2020-12) per event, plus docs/event-catalogue.md

Usage: python3 docs/tools/build_gate0.py
"""
import json
import re
from collections import OrderedDict, defaultdict
from pathlib import Path

import yaml

from build_stakeholder_views import DOCS, PLATFORM, STATUS_ORDER, load_stakeholders, norm

ROOT = DOCS.parent
OPENAPI_DIR = ROOT / "contracts" / "openapi"
OVERLAY_DIR = OPENAPI_DIR / "overlays"  # hand-written detail merged into the generated specs
EVENTS_DIR = ROOT / "contracts" / "events"
GENERATED = "Generated by docs/tools/build_gate0.py — do not edit by hand; edit the sources and re-run."

# ───────────────────────────── catalogue ─────────────────────────────

ROW = re.compile(r"^\| `([A-Z]+) ([^`]+)`([^|]*)\|([^|]*)\| (W|M|P|\?) \| (\d) \| ([^|]*)\|", re.M)


def load_catalogue():
    """Return {"METHOD /path": op} merging variants (type=, formType=, channel=, kind=)."""
    text = (DOCS / "endpoint-catalogue.md").read_text(encoding="utf-8").split("## 14.")[0]
    ops = OrderedDict()
    section = None
    for line in text.splitlines():
        h = re.match(r"## (\d+)\. (.+)", line)
        if h:
            section = h.group(2).strip()
            continue
        m = ROW.match(line)
        if not m:
            continue
        method, raw_path, marks, fn, status, phase, owner = m.groups()
        key = norm(f"{method} {raw_path}")
        query = raw_path.split("?", 1)[1] if "?" in raw_path else ""
        variant = re.search(r"`([a-zA-Z]+)=([A-Z0-9_]+)`", marks)
        fn = re.sub(r"\*\*|`", "", fn).strip()
        op = ops.get(key)
        if op is None:
            op = ops[key] = {
                "method": method, "path": key.split(" ", 1)[1], "section": section, "summary": fn,
                "status": status, "phase": int(phase), "owner": owner.strip(), "money": False,
                "step_up": False, "query": [q.split("=")[0] for q in query.split("&") if q], "variants": [],
            }
        if STATUS_ORDER[status] < STATUS_ORDER[op["status"]]:
            op["status"], op["phase"] = status, int(phase)
        op["money"] |= "💰" in marks
        op["step_up"] |= "🔐" in marks
        if variant:
            op["variants"].append({"field": variant.group(1), "value": variant.group(2), "status": status,
                                   "phase": int(phase), "summary": fn})
    for ep in PLATFORM:
        method, path = ep.split(" ", 1)
        ops.setdefault(ep, {"method": method, "path": path, "section": "Platform (init.md §3.1)",
                            "summary": "Platform endpoint defined in init.md §3.1", "status": "W", "phase": 1,
                            "owner": platform_owner(path), "money": False, "step_up": False, "query": [], "variants": []})
    return ops


def platform_owner(path):
    return {"monitoring": "reporting", "ai": "intelligence", "audit": "audit", "ndc": "platform"}[path.split("/")[1]]


# ───────────────────────────── scope rules ─────────────────────────────

SCOPE_RULES = [
        ("/public/", "anyone (rate-limited; lookups need CAPTCHA/OTP proof)"),
        ("/members/me", "self — caller's own member record only"),
        ("/members/uan", "unauthenticated with OTP / face-auth proof"),
        ("/pensioners/me", "self — caller's own PPO only"),
        ("/claimants/", "self — claimant's own claims only"),
        ("/employers/me", "own establishment (X-Establishment-Id validated against grants)"),
        ("/employers/registration-requests", "own registration request"),
        ("/employers/voluntary", "own registration request"),
        ("/exempted/me", "own exempted establishment"),
        ("/office/", "office jurisdiction of the caller's posting"),
        ("/do/", "district jurisdiction"),
        ("/zo/", "zone jurisdiction"),
        ("/ho/", "national (Head Office role)"),
        ("/cpps/", "national (CPPS service role)"),
        ("/governance/", "board members — aggregates only"),
        ("/monitoring/", "role jurisdiction; aggregates with small-group suppression"),
        ("/audit/", "read-only for auditors; audit writes by audit roles only"),
        ("/vigilance/", "restricted — vigilance roles only, case-by-case"),
        ("/privacy/", "data-protection officer only"),
        ("/security/me", "self — open to every authenticated caller (own data only)"),
        ("/security/step-up", "self — challenge bound to one action and resource version"),
        ("/security/", "security analyst"),
        ("/internal/", "service-to-service only (client credentials)"),
        ("/integrations/", "signed partner callback (signature, event ID, replay window)"),
        ("/partners/", "authenticated partner client, own records only"),
        ("/international/", "own application (employer) or IWU role"),
        ("/grievances/", "complainant or the assigned office"),
        ("/caiu/", "CAIU role"),
        ("/ai/", "caller's own permissions; advisory output only"),
        ("/hrm/", "self (read) / HR role (write)"),
        ("/ndc/", "NDC / IS operations role"),
        ("/training/", "training administrators; synthetic data only"),
        ("/vigilance", "restricted"),
]


def scope_prefix(path):
    return next((p for p, _ in SCOPE_RULES if path.startswith(p)), path)


def scope_of(path):
    """Data scope the gateway and service must enforce for a path."""
    return next((scope for prefix, scope in SCOPE_RULES if path.startswith(prefix)), "to be defined")


# Negative tests required by init.md §6.2, plus ones implied by the activity map.
# (id, actor, endpoint, case, rule[, expected]); expected defaults to "403 (404 where existence must stay hidden) + audit event"
MUST_DENY = [
    ("DENY-01", "member", "GET /members/me/accounts/{accountLinkId}/passbook", "Another member's accountLinkId", "Cross-UAN read"),
    ("DENY-02", "employer.operator", "GET /employers/me/ecr-filings/{filingId}", "Filing of an establishment the operator has no grant for", "Cross-establishment ECR read"),
    ("DENY-03", "employer.operator", "POST /employers/me/ecr-filings/{filingId}/approvals", "Operator approves the filing they prepared", "Payroll self-approval (separation of duties)"),
    ("DENY-04", "employer.signatory", "POST /employers/me/ecr-filings/{filingId}/submissions", "Signatory revoked seconds earlier, session still open", "Revoked signatory (§6.6, ≤ 5 s)"),
    ("DENY-05", "fo.apfc", "POST /office/cases/{caseId}/decisions", "Case belongs to another office's jurisdiction", "Cross-jurisdiction claim decision"),
    ("DENY-06", "gov.mole", "GET /office/members/{uan}", "Ministry viewer requests an individual member", "Ministry access to raw PII"),
    ("DENY-07", "tech.ndc", "GET /members/me/passbook", "NDC operator requests member financial data", "NDC operations access to financial data"),
    ("DENY-08", "ho.audit", "POST /office/cases/{caseId}/decisions", "Auditor attempts a write", "Auditor writes"),
    ("DENY-09", "tech.ai_service", "POST /office/claims/{claimId}/payment-instructions", "AI service account issues a payment", "AI issuing payment"),
    ("DENY-10", "tech.ai_service", "POST /office/cases/{caseId}/decisions", "AI service account approves a claim", "AI approving claims"),
    ("DENY-11", "payroll_provider", "GET /employers/me/members", "Partner pages through members of establishments it does not serve", "Partner bulk member enumeration"),
    ("DENY-12", "fo.ss", "POST /office/cases/{caseId}/decisions", "Claim amount above the SS band", "Approver outside their amount band"),
    ("DENY-13", "fo.da_accounts", "POST /office/cases/{caseId}/second-approvals", "Recommender also approves the same case", "Maker = checker"),
    ("DENY-14", "fo.da_accounts", "POST /office/ledger-adjustments/{adjustmentId}/approvals", "DA approves an Appendix-E / VDR Special credit", "Exceptional credit without RPFC-II (F&A) approval"),
    ("DENY-15", "member", "POST /members/me/claims", "Account is frozen", "Claim on a frozen account (FIA SOP 4.7)"),
    ("DENY-16", "public", "POST /public/pension/life-certificate-lookups", "No CAPTCHA / OTP proof, repeated identifiers", "Enumeration of pensioners"),
    ("DENY-17", "ext.collecting_bank", "POST /integrations/mock-bank/payment-confirmations", "Replayed callback or bad signature", "Falsified or replayed bank callback", "401 / 409, no state change"),
    ("DENY-18", "employer.operator", "POST /employers/me/ecr-filings", "Operator revoked while a browser session is open", "Revoked operator (§6.6, ≤ 5 s)"),
    ("DENY-19", "employer.operator", "GET /employers/me/members", "Grant removed for establishment X, still valid for Y; request for X", "Grant-scoped revocation (Y must still work)"),
    ("DENY-20", "member", "POST /members/me/claims/{claimId}/confirmations", "Step-up token replayed, expired, or issued for another claim / amount", "Step-up binding (§6.3)", "403, token consumed or rejected"),
    ("DENY-21", "fo.cash", "POST /office/claims/{claimId}/payment-instructions", "Claim still AWAITING_NEXT_APPROVAL or has an open risk signal", "Payment before the full approval chain", "409"),
    ("DENY-22", "fo.cash", "POST /office/claims/{claimId}/payment-instructions", "Account frozen between approval and payment", "Frozen claim racing to payment", "409"),
    ("DENY-23", "ext.collecting_bank", "POST /integrations/mock-bank/payment-confirmations", "Same valid callback delivered twice, or out of order", "No duplicate posting, settlement or notification", "200 with the original result; exactly one journal"),
    ("DENY-24", "tech.ai_service", "POST /ai/knowledge/search", "Retrieval would return another member's document", "Permission-filtered retrieval (init.md §8.2)", "Document excluded before model context is built"),
    ("DENY-25", "employer.operator", "GET /employers/me/ecr-filings/{filingId}", "Forged X-Establishment-Id for an establishment with no grant", "Forged establishment reference"),
]

# 21 interfaces from init.md §2.3 -> stakeholder IDs.
INTERFACES = [
    (1, "Public", ["public", "complainant", "rti_applicant"]),
    (2, "Employer", ["employer.owner", "employer.signatory", "employer.operator", "principal_employer", "contractor", "exempted.trust", "trust_auditor", "liquidator"]),
    (3, "Member", ["member", "member.exited", "member.disabled", "pensioner", "family_pensioner", "claimant", "csc_operator"]),
    (4, "Office", ["fo.da_accounts", "fo.da_compliance", "fo.ss", "fo.ao", "fo.cash", "fo.diary", "fo.da_pension", "fo.ss_pension", "fo.apfc_pension", "fo.pension_disbursement", "fo.eo", "fo.icf", "fo.recovery_officer", "fo.legal", "fo.exemption", "fo.edli", "fo.nan", "fo.admin"]),
    (5, "Grievance", ["fo.pro", "ho.customer_service", "ext.cpgrams"]),
    (6, "International worker", ["intl_worker", "fo.iw", "ho.iwu", "ext.foreign_ss"]),
    (7, "District office", ["do.incharge", "do.staff"]),
    (8, "Regional office", ["fo.apfc", "fo.rpfc1", "fo.oic"]),
    (9, "Zonal office", ["zo.acc", "zo.rpfc1", "zo.fraud_committee", "zo.zti"]),
    (10, "Head office", ["ho.cpfc", "ho.acc_hq", "ho.fa_cao", "ho.compliance", "ho.recovery", "ho.legal", "ho.exemption", "ho.pension", "ho.edli", "ho.investment", "ho.actuarial", "ho.publicity", "ho.is"]),
    (11, "NDC", ["tech.ndc", "tech.adc", "tech.cpps", "tech.epfo3"]),
    (12, "Ministry", ["gov.mole", "gov.parliament"]),
    (13, "B2B", ["payroll_provider", "ext.collecting_bank", "ext.pension_bank", "ext.mca", "ext.shram_suvidha", "ext.fund_manager"]),
    (14, "CAIU", ["ho.caiu"]),
    (15, "HRM", ["ho.hr"]),
    (16, "Reporting and monitoring", ["gov.cbt", "gov.ec", "gov.fiac", "gov.peic"]),
    (17, "Security", ["ho.security", "ho.data_protection"]),
    (18, "Vigilance", ["ho.cvo", "zo.vigilance"]),
    (19, "Audit", ["ho.audit", "zo.rpfc1_audit", "zo.internal_audit", "gov.cag", "gov.statutory_auditor"]),
    (20, "UMANG", ["ext.umang"]),
    (21, "AI model / local LLM", ["tech.ai_service"]),
]

# ───────────────────────────── events ─────────────────────────────

S, N, D, B, E = "string", "number", "date-time", "boolean", "enum"
# One balanced-journal line as seen by consumers (no names or identifiers beyond the opaque account link).
POSTINGS = {"type": "array", "minItems": 1, "items": {
    "type": "object", "additionalProperties": False, "required": ["account_code", "side", "amount_paise"],
    "properties": {
        "account_code": {"enum": ["AC01_EPF", "AC02_ADMIN", "AC10_EPS", "AC21_EDLI", "AC22_EDLI_ADMIN", "BANK_COLLECTION",
                                  "SUSPENSE_RECEIPTS", "CLAIMS_PAYABLE", "BANK_SETTLEMENT", "DAMAGES_INTEREST"]},
        "side": {"enum": ["debit", "credit"]},
        "account_link_id": {"type": "string", "description": "Opaque member account link, for member sub-ledger lines"},
        "share": {"enum": ["employee", "employer"]},
        "amount_paise": {"type": "integer", "minimum": 0}}}}
EVENTS = [
    # name, producer, consumers, aggregate, phase, payload {field: type}
    ("EmployerVerified", "employer", ["reporting", "audit"], "establishment", 1, {"establishment_id": S, "verification_ref": S}),
    ("EmployerOperatorRevoked", "employer", ["gateway", "audit"], "establishment", 1, {"establishment_id": S, "operator_subject": S, "grant_id": S, "scope": {"enum": ["grant", "subject"]}, "revoked_by": S}),
    ("SignatoryRevoked", "employer", ["gateway", "audit"], "establishment", 1, {"establishment_id": S, "signatory_subject": S, "grant_id": S, "scope": {"enum": ["grant", "subject"]}, "revoked_by": S}),
    ("ECRValidated", "contribution", ["reporting"], "ecr_filing", 1, {"filing_id": S, "establishment_id": S, "wage_month": S, "member_count": N}),
    ("ECRSubmitted", "contribution", ["payment-simulator", "reporting", "audit"], "ecr_filing", 1, {"filing_id": S, "establishment_id": S, "trrn": S, "total_paise": N, "rule_version": S}),
    ("PaymentConfirmed", "payment-simulator", ["contribution", "claim", "workflow", "audit"], "payment", 1, {"payment_id": S, "purpose": {"enum": ["CHALLAN", "CLAIM_SETTLEMENT", "DEMAND"]}, "reference_type": {"enum": ["trrn", "claim", "demand"]}, "reference_id": S, "amount_paise": N, "mock": B}),
    ("ContributionPosted", "contribution", ["member", "reporting", "audit"], "ledger_journal", 1, {"journal_id": S, "payment_id": S, "filing_id": S, "establishment_id": S, "wage_month": S, "postings": POSTINGS}),
    ("ClaimDebitPosted", "contribution", ["claim", "member", "audit"], "ledger_journal", 1, {"journal_id": S, "claim_id": S, "postings": POSTINGS}),
    ("ClaimSubmitted", "claim", ["workflow", "intelligence", "reporting", "audit"], "claim", 1, {"claim_id": S, "form_type": S, "amount_paise": N, "rule_version": S, "office_id": S, "account_link_id": S, "route": {"enum": ["AUTO", "REVIEW"]}, "advisory_signal_id": {"type": ["string", "null"]}, "claim_type": S}),
    ("CaseDecisionSubmitted", "workflow", ["claim", "audit"], "case", 1, {"case_id": S, "claim_id": S, "decision": {"enum": ["RECOMMEND", "APPROVE", "REJECT", "RETURN"]}, "officer_subject": S, "officer_role": S, "approval_level": N, "final": B, "next_role": {"type": ["string", "null"]}, "reason": {"type": ["string", "null"]}}),
    ("ClaimDecisionRecorded", "claim", ["member", "reporting", "audit"], "claim", 1, {"claim_id": S, "decision": {"enum": ["APPROVED", "AUTO_APPROVED", "REJECTED"]}, "reason_code": S, "rule_version": S, "amount_paise": N, "account_link_id": S}),
    ("PaymentInstructed", "claim", ["payment-simulator", "audit"], "claim", 1, {"claim_id": S, "payment_id": S, "amount_paise": N, "attempt": N, "demo_scenario": {"enum": ["SUCCESS", "RETURN"]}}),
    ("PaymentReturned", "payment-simulator", ["claim", "audit"], "payment", 1, {"payment_id": S, "purpose": {"enum": ["CHALLAN", "CLAIM_SETTLEMENT", "DEMAND"]}, "reference_type": {"enum": ["trrn", "claim", "demand"]}, "reference": S, "return_reason": S, "mock": B}),
    ("GrievanceRegistered", "grievance", ["workflow", "reporting", "intelligence", "audit"], "grievance", 1, {"grievance_id": S, "category": S, "office_id": S, "linked_claim_id": S}),
    ("GrievanceEscalated", "grievance", ["workflow", "reporting", "audit"], "grievance", 1, {"grievance_id": S, "from_tier": S, "to_tier": S, "office_id": S}),
    ("GrievanceResolved", "grievance", ["workflow", "reporting", "audit"], "grievance", 1, {"grievance_id": S, "office_id": S, "tier": {"enum": ["RO", "ZO", "HO"]}, "within_sla": B}),
    ("RiskSignalRaised", "intelligence", ["claim", "workflow", "reporting", "audit"], "risk_signal", 1, {"signal_id": S, "detection_type": S, "rule_version": S, "evidence_refs": "array", "subject_ref": S, "explanation": S}),
    ("ProcessTransitioned", "workflow", ["member", "contribution", "audit"], "process_instance", 1, {"process": S, "instance_id": S, "subject_ref": S, "from_state": {"type": ["string", "null"]}, "to_state": S, "operation": S, "title": S, "terminal": B, "visible_to_member": B, "actor_subject": S, "actor_role": S, "data": {"type": "object"}}),
    ("MemberExitMarked", "member", ["contribution", "claim", "workflow", "audit"], "member_account", 1, {"uan": S, "account_link_id": S, "date_of_exit": S, "reason": S, "marked_by": {"enum": ["MEMBER", "EMPLOYER"]}}),
    ("MemberRegistered", "member", ["contribution", "claim", "workflow", "audit"], "member_account", 1, {"uan": S, "account_link_id": S, "member_subject": {"type": ["string", "null"]}, "name": S, "date_of_birth": S, "gender": S, "establishment_id": S, "date_of_joining": S, "new_uan": B, "pan_verified": B}),
    ("MemberKycUpdated", "member", ["claim", "audit"], "member", 1, {"uan": S, "kyc_type": {"enum": ["PAN", "BANK", "AADHAAR"]}, "status": S, "pan_verified": B, "bank_ifsc": S, "bank_account_last4": S}),
    ("TransferPosted", "contribution", ["claim", "member", "workflow", "audit"], "ledger_journal", 1, {"transfer_id": S, "uan": S, "from_account_link_id": S, "to_account_link_id": S, "employee_paise": N, "employer_paise": N, "journal_id": S, "postings": POSTINGS}),
    ("PolicyPublished", "platform", ["claim", "contribution", "workflow", "grievance", "intelligence", "pension", "audit"], "rule_set", 1, {"version_id": S, "rule_version": S, "effective_from": S, "document_sha256": S, "approved_by_role": S, "document": {"type": "object"}}),
    ("ClaimStateChanged", "claim", ["workflow", "reporting", "audit"], "claim", 1, {"claim_id": S, "from_state": S, "to_state": S, "reason": S, "claim_type": S, "amount_paise": N, "rule_version": S, "office_id": S, "account_link_id": S}),
    ("RiskSignalReviewed", "intelligence", ["claim", "reporting", "audit"], "risk_signal", 1, {"signal_id": S, "subject_ref": S, "outcome": {"enum": ["CONFIRMED", "BENIGN", "NEEDS_MORE_EVIDENCE"]}}),
    ("SecurityEventRecorded", "audit", ["intelligence", "member", "gateway"], "security_event", 1, {"subject": S, "event_type": S, "device_fingerprint_hash": S}),
    ("NotificationRequested", ["claim", "grievance", "member", "contribution"], ["member"], "notification", 1, {"recipient_subject": S, "template": S, "reference_id": S, "params": {"type": "object"}}),
    ("DemandRaised", "compliance", ["contribution", "audit"], "compliance_case", 2, {"demand_id": S, "establishment_id": S, "demand_type": S, "amount_paise": N}),
    ("LedgerReversed", "contribution", ["claim", "reporting", "audit"], "ledger_journal", 1, {"journal_id": S, "reverses_journal_id": S, "reason": S, "claim_id": S, "postings": POSTINGS}),
    ("InterestCredited", "contribution", ["claim", "reporting", "audit"], "interest_run", 1, {"financial_year": S, "rate_bp": N, "rule_version": S, "postings": "array"}),
    ("TaxDeducted", "claim", ["contribution", "reporting", "audit"], "claim", 1, {"claim_id": S, "account_link_id": S, "gross_paise": N, "tds_paise": N, "net_paise": N, "rate_bp": N, "rule_version": S, "financial_year": S, "basis": S}),
    ("PaymentScrollGenerated", "claim", ["payment-simulator", "audit"], "payment_scroll", 1, {"scroll_id": S, "claim_ids": "array", "total_paise": N}),
    ("MemberChangeApproved", "member", ["contribution", "claim", "reporting", "audit"], "member_change_request", 1, {"request_id": S, "uan": S, "parameters": "array", "approver_subject": S}),
    ("AccountFrozen", "member", ["gateway", "claim", "audit"], "account", 1, {"target_type": S, "target_id": S, "category": S, "order_ref": S}),
    ("AccountDefrozen", "member", ["gateway", "claim", "audit"], "account", 1, {"target_type": S, "target_id": S, "order_ref": S}),
    ("PpoIssued", "pension", ["member", "reporting", "audit"], "pension_claim", 2, {"ppo_id": S, "pension_type": S, "office_id": S}),
    ("LifeCertificateRecorded", "pension", ["reporting", "audit"], "pensioner", 2, {"ppo_id": S, "valid_until": S, "source": S}),
    # From the Samadhan Setu integration spec (payloads converted to paise / basis points, no member identifiers)
    ("CADGenerated", "claim", ["contribution", "payment-simulator", "audit"], "claim", 1, {"claim_id": S, "cad_id": S, "net_payable_paise": N, "tds_paise": N, "rule_version": S, "static_data_version": S}),
    ("BeneficiaryShareAmended", "claim", ["reporting", "audit"], "claim", 2, {"claim_id": S, "beneficiary_id": S, "previous_share_bp": {"type": "integer", "minimum": 0, "maximum": 10000}, "new_share_bp": {"type": "integer", "minimum": 0, "maximum": 10000}, "reason_code": {"enum": ["NOMINEE_DECEASED", "COURT_ORDER", "LEGACY_SETTLEMENT_OFFSET", "GUARDIAN_APPOINTMENT"]}, "amended_by": S}),
    ("SupplementaryClaimEligible", "contribution", ["member", "claim", "audit"], "ledger_journal", 2, {"account_link_id": S, "settled_claim_id": S, "late_credit_paise": N, "credit_source": {"enum": ["TRANSFER_IN", "CONTRIBUTION", "RECREDIT"]}}),
    ("LockReleased", "workflow", ["audit", "reporting"], "ledger_lock", 2, {"lock_id": S, "lock_scope": {"enum": ["ANNUAL_ACCOUNTING", "CLAIM_ADJUDICATION", "ECR_POSTING"]}, "resource_key": S, "released_by": S, "reason": {"type": "string", "minLength": 10}}),
]


def event_schema(name, producer, aggregate, payload):
    props = {}
    for field, typ in payload.items():
        if isinstance(typ, dict):
            props[field] = typ
        else:
            props[field] = {"type": "array", "items": {"type": "string"}} if typ == "array" else {"type": typ}
        if field.endswith("_paise"):
            props[field] = {"type": "integer", "minimum": 0, "description": "Money in paise (integer); never floating point"}
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"https://epfo-poc.example/contracts/events/{name}.v1.schema.json",
        "title": f"{name}.v1",
        "description": f"{GENERATED} Synthetic POC event; minimum necessary payload, no raw PII.",
        "type": "object",
        "additionalProperties": False,
        "required": ["event_id", "event_type", "schema_version", "aggregate_type", "aggregate_id", "producer",
                     "occurred_at", "correlation_id", "payload"],
        "properties": {
            "event_id": {"type": "string", "format": "uuid"},
            "event_type": {"const": f"{name}.v1"},
            "schema_version": {"const": 1},
            "aggregate_type": {"const": aggregate},
            "aggregate_id": {"type": "string"},
            "producer": ({"enum": [f"{p}-service" for p in producer]} if isinstance(producer, list) else
                         {"const": f"{producer}-service" if producer not in ("payment-simulator",) else producer}),
            "occurred_at": {"type": "string", "format": "date-time", "description": "UTC"},
            "correlation_id": {"type": "string", "format": "uuid"},
            "causation_id": {"type": "string", "format": "uuid", "description": "Optional: the event that caused this one, when there is one"},
            "payload": {"type": "object", "additionalProperties": False, "required": list(payload), "properties": props},
        },
    }


# ───────────────────────────── OpenAPI ─────────────────────────────

def op_id(method, path):
    words = [w for w in re.split(r"[/{}\-_?=&]+", path) if w and w != "me"]
    base = "".join(w[:1].upper() + w[1:] for w in words)
    return method.lower() + base


def components():
    return {
        "securitySchemes": {
            "bffSession": {"type": "apiKey", "in": "cookie", "name": "__Host-epfo-session",
                           "description": "Gateway session cookie (init.md §2.1, §6.6)"},
            "clientCredentials": {"type": "oauth2", "flows": {"clientCredentials": {"tokenUrl": "http://localhost:8080/realms/epfo-demo/protocol/openid-connect/token", "scopes": {}}}},
        },
        "parameters": {
            "IdempotencyKey": {"name": "Idempotency-Key", "in": "header", "required": True, "schema": {"type": "string", "maxLength": 128},
                               "description": "Required on money-changing and filing commands (init.md §3.3)"},
            "IfMatch": {"name": "If-Match", "in": "header", "required": True, "schema": {"type": "string"},
                        "description": "Aggregate version for optimistic concurrency"},
            "CorrelationId": {"name": "X-Correlation-Id", "in": "header", "required": False, "schema": {"type": "string", "format": "uuid"}},
            "EstablishmentId": {"name": "X-Establishment-Id", "in": "header", "required": True, "schema": {"type": "string"},
                                "description": "Active establishment; validated server-side against the caller's grants"},
            "StepUpToken": {"name": "X-Step-Up-Token", "in": "header", "required": True, "schema": {"type": "string"},
                            "description": "Proof of a completed step-up / transaction-intent confirmation (init.md §6.3)"},
        },
        "schemas": {
            "Problem": {"type": "object", "description": "RFC 9457 Problem Details",
                        "required": ["type", "title", "status", "correlation_id"],
                        "properties": {"type": {"type": "string", "format": "uri-reference"}, "title": {"type": "string"},
                                       "status": {"type": "integer"}, "detail": {"type": "string"},
                                       "correlation_id": {"type": "string", "format": "uuid"}}},
            "Meta": {"type": "object", "required": ["correlation_id", "api_version", "source", "as_of"],
                     "properties": {"correlation_id": {"type": "string", "format": "uuid"}, "api_version": {"const": "v1"},
                                    "source": {"const": "synthetic-poc"}, "as_of": {"type": "string", "format": "date-time"}}},
            "Envelope": {"type": "object", "required": ["data", "meta"],
                         "properties": {"data": {"type": "object", "description": "Resource-specific; defined when the endpoint is implemented"},
                                        "meta": {"$ref": "#/components/schemas/Meta"}}},
        },
        "responses": {
            "Ok": {"description": "Success", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Envelope"}}}},
            "Created": {"description": "Created", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Envelope"}}}},
            "Problem": {"description": "Error (RFC 9457)", "content": {"application/problem+json": {"schema": {"$ref": "#/components/schemas/Problem"}}}},
            "Planned": {"description": "Planned contract — not implemented in this POC. Returns type /problems/planned; never a fake success.",
                        "content": {"application/problem+json": {"schema": {"$ref": "#/components/schemas/Problem"}}}},
        },
    }


def operation(op, callers):
    params = [{"$ref": "#/components/parameters/CorrelationId"}]
    for name in re.findall(r"{(\w+)}", op["path"]):
        params.append({"name": name, "in": "path", "required": True, "schema": {"type": "string"}})
    for q in op["query"]:
        params.append({"name": q, "in": "query", "required": False, "schema": {"type": "string"}})
    if op["path"].startswith("/employers/me"):
        params.append({"$ref": "#/components/parameters/EstablishmentId"})
    if op["money"]:
        params += [{"$ref": "#/components/parameters/IdempotencyKey"}, {"$ref": "#/components/parameters/IfMatch"}]
    if op["step_up"]:
        params.append({"$ref": "#/components/parameters/StepUpToken"})
    ref = lambda r: {"$ref": f"#/components/responses/{r}"}
    if op["status"] in ("P", "?"):
        responses = {"501": ref("Planned"), "401": ref("Problem"), "403": ref("Problem")}
    else:
        ok = "201" if op["method"] == "POST" else "200"
        responses = {ok: ref("Created" if ok == "201" else "Ok"), "400": ref("Problem"), "401": ref("Problem"),
                     "403": ref("Problem"), "404": ref("Problem"), "409": ref("Problem")}
    out = {
        "operationId": op_id(op["method"], op["path"]),
        "summary": op["summary"][:120],
        "tags": [op["section"]],
        "parameters": params,
        "responses": responses,
        "x-status": {"W": "working", "M": "mock", "P": "planned", "?": "definition-pending"}[op["status"]],
        "x-phase": op["phase"],
        "x-owner-service": op["owner"],
        "x-callers": sorted(callers),
        "x-scope": scope_of(op["path"]),
        "security": [] if op["path"].startswith("/public/") else ([{"clientCredentials": []}] if op["path"].startswith(("/integrations/", "/internal/", "/partners/")) else [{"bffSession": []}]),
    }
    if len(op["summary"]) > 120:
        out["description"] = op["summary"]
    if op["variants"]:
        field = op["variants"][0]["field"]
        out["x-variants"] = [{field: v["value"], "status": v["status"], "phase": v["phase"]} for v in op["variants"]]
        out["description"] = (out.get("description", "") + f"\n\nVariants by `{field}`: " +
                              "; ".join(f"`{v['value']}` ({v['status']}, phase {v['phase']})" for v in op["variants"])).strip()
    if op["method"] in ("POST", "PUT", "PATCH"):
        out["requestBody"] = {"required": op["method"] != "POST" or not op["path"].endswith("s"),
                              "content": {"application/json": {"schema": {"type": "object", "description": "Defined when implemented"}}}}
    return out


def load_overlays():
    """{spec file stem: overlay dict}. Overlays add request/response schemas; they never change status or callers."""
    overlays = {}
    for f in sorted(OVERLAY_DIR.glob("*.yaml")) if OVERLAY_DIR.exists() else []:
        overlays[f.stem] = yaml.safe_load(f.read_text(encoding="utf-8")) or {}
    return overlays


def apply_overlay(doc, overlay, source):
    for path, methods in (overlay.get("paths") or {}).items():
        for method, fields in methods.items():
            target = doc["paths"].get(path, {}).get(method)
            if target is None:
                raise SystemExit(f"overlay {source}: {method.upper()} {path} is not in the catalogue")
            for key, value in fields.items():
                if key == "responses":
                    target["responses"].update(value)          # keeps 501 for planned operations
                elif key == "parameters":
                    by_name = {p.get("name"): i for i, p in enumerate(target["parameters"]) if "name" in p}
                    for param in value:
                        if param.get("name") in by_name:
                            target["parameters"][by_name[param["name"]]] = param
                        else:
                            target["parameters"].append(param)
                elif key.startswith("x-status") or key in ("x-callers", "x-phase", "x-owner-service"):
                    raise SystemExit(f"overlay {source}: {key} comes from the catalogue, not overlays")
                else:
                    target[key] = value
    doc["components"]["schemas"].update((overlay.get("components") or {}).get("schemas") or {})


def spec(title, ops, callers, overlays=()):
    paths = {}
    for key, op in sorted(ops.items(), key=lambda kv: (kv[1]["path"], kv[1]["method"])):
        paths.setdefault(op["path"], {})[op["method"].lower()] = operation(op, callers.get(key, set()))
    doc = {
        "openapi": "3.1.0",
        "info": {"title": title, "version": "0.1.0-gate0",
                 "description": f"{GENERATED}\n\nSYNTHETIC DEMONSTRATION — NOT AN OFFICIAL EPFO SYSTEM. "
                                "x-status: working | mock | planned | definition-pending. Planned operations return 501 /problems/planned."},
        "servers": [{"url": "http://localhost:8000/api/v1", "description": "Gateway (init.md §2.4)"}],
        "paths": paths,
        "components": components(),
    }
    for source, overlay in overlays:
        apply_overlay(doc, overlay, source)
    return doc


def dump_yaml(data, path):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"# {GENERATED}\n" + yaml.safe_dump(data, sort_keys=False, allow_unicode=True, width=120), encoding="utf-8")


# ───────────────────────────── main ─────────────────────────────

def main():
    ops = load_catalogue()
    data = yaml.safe_load((DOCS / "stakeholder-activities.yaml").read_text(encoding="utf-8"))
    groups, names = load_stakeholders()
    acts = data["activities"]
    chains = data["approval_chains"]

    callers = defaultdict(set)          # endpoint -> stakeholders
    grants = defaultdict(OrderedDict)   # stakeholder -> endpoint -> activities
    for a in acts:
        for ep in a.get("api", []):
            key = norm(ep)
            if key not in ops:
                raise SystemExit(f"{a['id']}: {ep} not in catalogue — run build_stakeholder_views.py --check")
            callers[key].add(a["actor"])
            grants[a["actor"]].setdefault(key, []).append(a["id"])

    # permissions.yaml
    perm = {"generated": GENERATED, "stakeholders": {}}
    for s in names:
        perm["stakeholders"][s] = [{"endpoint": ep, "status": ops[ep]["status"], "scope": scope_of(ops[ep]["path"]),
                                    "step_up": ops[ep]["step_up"], "via": acts_} for ep, acts_ in grants.get(s, {}).items()]
    perm["separation_of_duties"] = {cid: c for cid, c in chains.items()}
    default_expected = "403 (404 where existence must stay hidden) + audit event"
    deny = [(*row[:5], row[5] if len(row) > 5 else default_expected) for row in MUST_DENY]
    perm["must_deny"] = [{"id": i, "actor": a, "endpoint": e, "case": c, "rule": r, "expected": x} for i, a, e, c, r, x in deny]
    dump_yaml(perm, DOCS / "permissions.yaml")

    # permissions.md
    out = ["# Permission Matrix", "", f"> {GENERATED} Machine-readable copy: `docs/permissions.yaml`.", "",
           "Default is **deny**. A stakeholder may call only the endpoints listed for it, only within the scope shown, "
           "and the owning service re-checks the grant on every write (init.md §6.6).", "",
           "## Scope rules by path", "", "| Path prefix | Scope enforced |", "|---|---|"]
    used = OrderedDict()
    for op in sorted(ops.values(), key=lambda o: o["path"]):
        used.setdefault(scope_prefix(op["path"]), scope_of(op["path"]))
    out += [f"| `{prefix}` | {scope} |" for prefix, scope in used.items()]
    out += ["", "## Separation of duties (approval chains)", "",
            "Maker and checker are always different people. Amount bands are illustrative configuration.", "",
            "| Chain | Route | Source |", "|---|---|---|"]
    for cid, c in chains.items():
        if c.get("bands"):
            route = "<br>".join(f"{'≤ ₹' + format(b['upto'], ',') if 'upto' in b else '> ₹' + format(b['above'], ',')}: "
                                + " → ".join(f"`{x}`" for x in b["chain"]) for b in c["bands"])
        else:
            route = " → ".join(f"`{x}`" for x in c.get("chain", []))
        out.append(f"| {cid} | {route} | {c.get('src', '')} |")
    out += ["", "## Must-deny tests (tests/security)", "",
            "Each row is a required negative or idempotency test in `tests/security/`.", "",
            "| ID | Actor | Endpoint | Case | Rule | Expected |", "|---|---|---|---|---|---|"]
    out += [f"| {i} | `{a}` | `{e}` | {c} | {r} | {x} |" for i, a, e, c, r, x in deny]
    out += ["", "## Grants by stakeholder", ""]
    for group, members in groups.items():
        out += [f"### {group}", ""]
        for s in members:
            g = grants.get(s)
            if not g:
                out += [f"- `{s}` — {names[s]}: *no endpoints (acts through an adapter or through another role)*"]
                continue
            out += ["", f"**`{s}`** — {names[s]}", "", "| Endpoint | Status | Scope | Step-up |", "|---|---|---|---|"]
            for ep in sorted(g, key=lambda e: (STATUS_ORDER[ops[e]["status"]], e)):
                out.append(f"| `{ep}` | {ops[ep]['status']} | {scope_of(ops[ep]['path'])} | {'yes' if ops[ep]['step_up'] else ''} |")
        out.append("")
    (DOCS / "permissions.md").write_text("\n".join(out) + "\n", encoding="utf-8")

    # api-matrix.md
    out = ["# API Matrix — 21 Interfaces", "", f"> {GENERATED}", "",
           "Coverage rule: **Working** if any Working endpoint serves the interface's stakeholders; else **Mock** if any Mock; "
           "else **Planned**. Every interface is recorded here as required by init.md §12.2.", "",
           "| # | Interface | Coverage | Stakeholders | W | M | P | ? |", "|---|---|---|---|---|---|---|---|"]
    detail = []
    for num, name, members in INTERFACES:
        eps = sorted({ep for s in members for ep in grants.get(s, {})}, key=lambda e: (STATUS_ORDER[ops[e]["status"]], e))
        cnt = {k: sum(ops[e]["status"] == k for e in eps) for k in "WMP?"}
        cov = "Working" if cnt["W"] else "Mock" if cnt["M"] else "Planned"
        out.append(f"| {num} | {name} | **{cov}** | {', '.join(f'`{m}`' for m in members)} | {cnt['W']} | {cnt['M']} | {cnt['P']} | {cnt['?']} |")
        detail += [f"### {num}. {name} — {cov}", "", "| Endpoint | Status | Owner | Called by |", "|---|---|---|---|"]
        detail += [f"| `{e}` | {ops[e]['status']} | {ops[e]['owner']} | {', '.join(sorted(callers[e] & set(members)))} |" for e in eps]
        detail.append("")
    (DOCS / "api-matrix.md").write_text("\n".join(out + ["", "## Detail", ""] + detail) + "\n", encoding="utf-8")

    # OpenAPI per service + gateway
    by_owner = defaultdict(OrderedDict)
    for key, op in ops.items():
        by_owner[op["owner"]][key] = op
    overlays = load_overlays()
    names = {}
    for owner, owned in by_owner.items():
        name = owner if owner in ("gateway", "platform", "payment-simulator") else f"{owner}-service"
        names[name] = owner
        own = [(name, overlays[name])] if name in overlays else []
        dump_yaml(spec(f"{name} API", owned, callers, own), OPENAPI_DIR / f"{name}.yaml")
    unknown = set(overlays) - set(names)
    if unknown:
        raise SystemExit(f"overlays for unknown services: {sorted(unknown)}")
    dump_yaml(spec("EPFO POC Gateway API (consolidated)", ops, callers, sorted(overlays.items())),
              OPENAPI_DIR / "gateway-consolidated.yaml")

    # Events
    EVENTS_DIR.mkdir(parents=True, exist_ok=True)
    rows = ["# Event Catalogue", "", f"> {GENERATED} Schemas: `contracts/events/`.", "",
            "Every event uses the same envelope (event ID, type, schema version, aggregate, producer, UTC time and correlation ID; "
            "`causation_id` is added when the event was caused by another event). Consumers must be idempotent by `event_id` and tolerate out-of-order delivery (init.md §3.3). "
            "Failed deliveries go to a DLQ and are replayed with `POST /ndc/event-failures/{eventId}/replays`.", "",
            "| Event | Producer | Consumers | Aggregate | Phase |", "|---|---|---|---|---|"]
    for name, producer, consumers, aggregate, phase, payload in EVENTS:
        (EVENTS_DIR / f"{name}.v1.schema.json").write_text(
            json.dumps(event_schema(name, producer, aggregate, payload), indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        rows.append(f"| `{name}.v1` | {', '.join(producer) if isinstance(producer, list) else producer} | {', '.join(consumers)} | {aggregate} | {phase}{' (contract only)' if phase > 1 else ''} |")
    (DOCS / "event-catalogue.md").write_text("\n".join(rows) + "\n", encoding="utf-8")

    print(f"permissions: {sum(len(v) for v in grants.values())} grants, {len(deny)} must-deny tests")
    print(f"api-matrix: {len(INTERFACES)} interfaces")
    print(f"openapi: {len(by_owner)} service specs + consolidated, {len(ops)} operations")
    print(f"events: {len(EVENTS)} schemas")


if __name__ == "__main__":
    main()
