"""The CAD is the Claim Approval Docket, regenerated by each officer before acting (P2.5d): several per claim.

Revision ID: 0011
"""
import sqlalchemy as sa
from alembic import op

revision = "0011"
down_revision = "0010"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.drop_constraint("cads_claim_id_key", "cads", type_="unique")
    op.create_index("ix_cads_claim_id", "cads", ["claim_id"])
    op.add_column("cads", sa.Column("officer_role", sa.String(60)))


def downgrade() -> None:
    op.drop_column("cads", "officer_role")
    op.drop_index("ix_cads_claim_id", table_name="cads")
    op.create_unique_constraint("cads_claim_id_key", "cads", ["claim_id"])
