"""GENERATED by packages/service-template/scaffold.py from docs/endpoint-catalogue.md — do not edit.

Phase-1 operations owned by this service. Until an operation is implemented, it verifies the caller's
internal token and answers 501 /problems/not-yet-built. Replace a stub by adding a real route with the
same method and path in app/api/routes.py; stubs are only registered for paths not already routed."""
from fastapi import APIRouter, Depends

from epfo_auth import Actor, require_actor
from epfo_observability import Problem

router = APIRouter()

OPERATIONS = ['GET /monitoring/claims', 'GET /monitoring/contributions', 'GET /monitoring/data-freshness', 'GET /monitoring/grievances', 'GET /public/schemes', 'GET /public/statistics', 'GET /zo/dashboards', 'GET /employers/me/compliance-summary', 'GET /office/compliance/defaulters', 'GET /public/establishments/{estId}/e-report-card']

@router.api_route("/api/v1/monitoring/claims", methods=["GET"], include_in_schema=False)
async def get_monitoring_claims(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Platform endpoint defined in init.md §3.1")


@router.api_route("/api/v1/monitoring/contributions", methods=["GET"], include_in_schema=False)
async def get_monitoring_contributions(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Platform endpoint defined in init.md §3.1")


@router.api_route("/api/v1/monitoring/data-freshness", methods=["GET"], include_in_schema=False)
async def get_monitoring_data_freshness(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Platform endpoint defined in init.md §3.1")


@router.api_route("/api/v1/monitoring/grievances", methods=["GET"], include_in_schema=False)
async def get_monitoring_grievances(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Platform endpoint defined in init.md §3.1")


@router.api_route("/api/v1/public/schemes", methods=["GET"], include_in_schema=False)
async def get_public_schemes(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Scheme catalogue (EPF, EPS, EDLI) — illustrative text")


@router.api_route("/api/v1/public/statistics", methods=["GET"], include_in_schema=False)
async def get_public_statistics(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Aggregate statistics, small-group suppression")


@router.api_route("/api/v1/zo/dashboards", methods=["GET"], include_in_schema=False)
async def get_zo_dashboards(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Zonal comparison dashboard (interface 9, aggregated, read-only)")


@router.api_route("/api/v1/employers/me/compliance-summary", methods=["GET"], include_in_schema=False)
async def get_employers_me_compliance_summary(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Month-wise filing / payment compliance for this establishment")


@router.api_route("/api/v1/office/compliance/defaulters", methods=["GET"], include_in_schema=False)
async def get_office_compliance_defaulters(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Non-filing / short-payment detection")


@router.api_route("/api/v1/public/establishments/{estId}/e-report-card", methods=["GET"], include_in_schema=False)
async def get_public_establishments_estId_e_report_card(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Establishment e-Report Card: wage-month filing/payment history, counts and totals only")
