"""GENERATED by packages/service-template/scaffold.py from docs/endpoint-catalogue.md — do not edit.

Phase-1 operations owned by this service. Until an operation is implemented, it verifies the caller's
internal token and answers 501 /problems/not-yet-built. Replace a stub by adding a real route with the
same method and path in app/api/routes.py; stubs are only registered for paths not already routed."""
from fastapi import APIRouter, Depends

from epfo_auth import Actor, require_actor
from epfo_observability import Problem

router = APIRouter()

OPERATIONS = ['GET /do/dashboards', 'GET /governance/board-packs', 'GET /monitoring/claims', 'GET /monitoring/contributions', 'GET /monitoring/data-freshness', 'GET /monitoring/grievances', 'GET /public/schemes', 'GET /public/service-standards', 'GET /public/statistics', 'GET /zo/dashboards', 'GET /employers/me/compliance-summary', 'GET /employers/me/dashboard', 'GET /ho/finance/investments', 'POST /integrations/fund-managers/positions', 'GET /office/compliance/defaulters', 'GET /employers/me/contractors/{contractorId}/compliance', 'GET /public/establishments/{estId}/e-report-card']

@router.api_route("/api/v1/do/dashboards", methods=["GET"], include_in_schema=False)
async def get_do_dashboards(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "District dashboard (interface 7)")


@router.api_route("/api/v1/governance/board-packs", methods=["GET"], include_in_schema=False)
async def get_governance_board_packs(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "CBT / EC / FIAC board packs (aggregates only)")


@router.api_route("/api/v1/monitoring/claims", methods=["GET"], include_in_schema=False)
async def get_monitoring_claims(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Platform endpoint defined in init.md §3.1")


@router.api_route("/api/v1/monitoring/contributions", methods=["GET"], include_in_schema=False)
async def get_monitoring_contributions(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Platform endpoint defined in init.md §3.1")


@router.api_route("/api/v1/monitoring/data-freshness", methods=["GET"], include_in_schema=False)
async def get_monitoring_data_freshness(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Platform endpoint defined in init.md §3.1")


@router.api_route("/api/v1/monitoring/grievances", methods=["GET"], include_in_schema=False)
async def get_monitoring_grievances(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Platform endpoint defined in init.md §3.1")


@router.api_route("/api/v1/public/schemes", methods=["GET"], include_in_schema=False)
async def get_public_schemes(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Scheme catalogue (EPF, EPS, EDLI) — illustrative text")


@router.api_route("/api/v1/public/service-standards", methods=["GET"], include_in_schema=False)
async def get_public_service_standards(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "The citizen's charter: each service standard (statutory or target) with live performance per office ")


@router.api_route("/api/v1/public/statistics", methods=["GET"], include_in_schema=False)
async def get_public_statistics(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Aggregate statistics, small-group suppression")


@router.api_route("/api/v1/zo/dashboards", methods=["GET"], include_in_schema=False)
async def get_zo_dashboards(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Zonal comparison dashboard (interface 9, aggregated, read-only)")


@router.api_route("/api/v1/employers/me/compliance-summary", methods=["GET"], include_in_schema=False)
async def get_employers_me_compliance_summary(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Month-wise filing / payment compliance for this establishment")


@router.api_route("/api/v1/employers/me/dashboard", methods=["GET"], include_in_schema=False)
async def get_employers_me_dashboard(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Employer home alerts and Dashboards (pending KYC, member-detail approvals, missing details)")


@router.api_route("/api/v1/ho/finance/investments", methods=["GET"], include_in_schema=False)
async def get_ho_finance_investments(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Investment reporting")


@router.api_route("/api/v1/integrations/fund-managers/positions", methods=["POST"], include_in_schema=False)
async def post_integrations_fund_managers_positions(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Fund manager / custodian position feed (signed)")


@router.api_route("/api/v1/office/compliance/defaulters", methods=["GET"], include_in_schema=False)
async def get_office_compliance_defaulters(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Non-filing / short-payment detection")


@router.api_route("/api/v1/employers/me/contractors/{contractorId}/compliance", methods=["GET"], include_in_schema=False)
async def get_employers_me_contractors_contractorId_compliance(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Principal employer: contractor remittance compliance")


@router.api_route("/api/v1/public/establishments/{estId}/e-report-card", methods=["GET"], include_in_schema=False)
async def get_public_establishments_estId_e_report_card(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Establishment e-Report Card: wage-month filing/payment history, counts and totals only")
