"""GENERATED by packages/service-template/scaffold.py from docs/endpoint-catalogue.md — do not edit.

Phase-1 operations owned by this service. Until an operation is implemented, it verifies the caller's
internal token and answers 501 /problems/not-yet-built. Replace a stub by adding a real route with the
same method and path in app/api/routes.py; stubs are only registered for paths not already routed."""
from fastapi import APIRouter, Depends

from epfo_auth import Actor, require_actor
from epfo_observability import Problem

router = APIRouter()

OPERATIONS = ['GET /pensioners/me/life-certificate', 'POST /public/pension/life-certificate-lookups']

@router.api_route("/api/v1/pensioners/me/life-certificate", methods=["GET"], include_in_schema=False)
async def get_pensioners_me_life_certificate(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Jeevan Pramaan / Digital Life Certificate status: last submitted, valid till, source")


@router.api_route("/api/v1/public/pension/life-certificate-lookups", methods=["POST"], include_in_schema=False)
async def post_public_pension_life_certificate_lookups(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Jeevan Pramaan / life-certificate status by PPO number or Jeevan Pramaan transaction ID (CAPTCHA, mi")
