"""GENERATED by packages/service-template/scaffold.py from docs/endpoint-catalogue.md — do not edit.

Phase-1 operations owned by this service. Until an operation is implemented, it verifies the caller's
internal token and answers 501 /problems/not-yet-built. Replace a stub by adding a real route with the
same method and path in app/api/routes.py; stubs are only registered for paths not already routed."""
from fastapi import APIRouter, Depends

from epfo_auth import Actor, require_actor
from epfo_observability import Problem

router = APIRouter()

OPERATIONS = ['GET /international/agreements', 'GET /international/coc-applications', 'POST /international/coc-applications', 'GET /members/me/international', 'GET /office/international/coc-applications', 'POST /office/international/coc-applications/{id}/decisions', 'GET /international/coc-applications/{id}', 'GET /international/coc-applications/{id}/certificate', 'POST /international/coc-applications/{id}/extensions', 'POST /international/coc-applications/{id}/signed-uploads']

@router.api_route("/api/v1/international/agreements", methods=["GET"], include_in_schema=False)
async def get_international_agreements(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Social-security agreement catalogue (synthetic, labelled)")


@router.api_route("/api/v1/international/coc-applications", methods=["GET"], include_in_schema=False)
async def get_international_coc_applications(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "The establishment's Certificate of Coverage applications")


@router.api_route("/api/v1/international/coc-applications", methods=["POST"], include_in_schema=False)
async def post_international_coc_applications(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Certificate of Coverage application (mock)")


@router.api_route("/api/v1/members/me/international", methods=["GET"], include_in_schema=False)
async def get_members_me_international(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "International worker profile")


@router.api_route("/api/v1/office/international/coc-applications", methods=["GET"], include_in_schema=False)
async def get_office_international_coc_applications(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Certificate of Coverage applications of the office's establishments")


@router.api_route("/api/v1/office/international/coc-applications/{id}/decisions", methods=["POST"], include_in_schema=False)
async def post_office_international_coc_applications_id_decisions(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "IW cell verification and CoC issuance (mock)")


@router.api_route("/api/v1/international/coc-applications/{id}", methods=["GET"], include_in_schema=False)
async def get_international_coc_applications_id(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "CoC status")


@router.api_route("/api/v1/international/coc-applications/{id}/certificate", methods=["GET"], include_in_schema=False)
async def get_international_coc_applications_id_certificate(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Download issued Certificate of Coverage")


@router.api_route("/api/v1/international/coc-applications/{id}/extensions", methods=["POST"], include_in_schema=False)
async def post_international_coc_applications_id_extensions(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "CoC extension / renewal")


@router.api_route("/api/v1/international/coc-applications/{id}/signed-uploads", methods=["POST"], include_in_schema=False)
async def post_international_coc_applications_id_signed_uploads(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Employer uploads signed CoC application")
