"""GENERATED by packages/service-template/scaffold.py from docs/endpoint-catalogue.md — do not edit.

Phase-1 operations owned by this service. Until an operation is implemented, it verifies the caller's
internal token and answers 501 /problems/not-yet-built. Replace a stub by adding a real route with the
same method and path in app/api/routes.py; stubs are only registered for paths not already routed."""
from fastapi import APIRouter, Depends

from epfo_auth import Actor, require_actor
from epfo_observability import Problem

router = APIRouter()

OPERATIONS = ['POST /claimants/death-claims', 'GET /office/annexure-k-files', 'POST /office/payment-scrolls', 'POST /office/physical-claims', 'GET /office/transfers', 'GET /employers/me/transfer-requests', 'GET /members/me/claims', 'POST /members/me/claims', 'POST /members/me/transfers', 'GET /office/payment-scrolls/ready', 'GET /office/system/cad-static-data', 'GET /members/me/claims/eligibility-preview', 'GET /members/me/claims/eligible-types', 'POST /members/me/tax/form-15g-15h', 'GET /members/me/claims/{claimId}', 'GET /members/me/transfers/{transferId}', 'POST /employers/me/transfer-requests/{transferId}/decisions', 'GET /members/me/claims/{claimId}/audit-trail', 'POST /members/me/claims/{claimId}/cancellations', 'POST /members/me/claims/{claimId}/confirmations', 'POST /members/me/claims/{claimId}/documents', 'POST /members/me/claims/{claimId}/re-disbursement-requests', 'GET /claimants/death-claims/{claimId}', 'POST /claimants/death-claims/{claimId}/beneficiaries', 'POST /office/annexure-k-files/{annexureId}/reconciliations', 'GET /office/claims/{claimId}/additional-forms', 'GET /office/claims/{claimId}/audit-trail', 'GET /office/claims/{claimId}/cad', 'POST /office/claims/{claimId}/cad', 'POST /office/claims/{claimId}/payment-instructions', 'POST /office/claims/{claimId}/re-disbursement-approvals', 'POST /office/claims/{claimId}/reissues', 'GET /office/death-claims/{claimId}/shares-summary', 'POST /office/payment-scrolls/{scrollId}/return-reconciliations', 'POST /office/transfers/{transferId}/decisions', 'POST /office/transfers/{transferId}/verifications', 'PUT /office/death-claims/{claimId}/beneficiaries/{beneficiaryId}/shares']

@router.api_route("/api/v1/claimants/death-claims", methods=["POST"], include_in_schema=False)
async def post_claimants_death_claims(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "PF death claim by nominee / legal heir")


@router.api_route("/api/v1/office/annexure-k-files", methods=["GET"], include_in_schema=False)
async def get_office_annexure_k_files(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "ANNEXURE K FILE — Annexure K inward / outward between field offices for Form 13 transfers")


@router.api_route("/api/v1/office/payment-scrolls", methods=["POST"], include_in_schema=False)
async def post_office_payment_scrolls(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Batch approved settlements into a payment scroll → PaymentScrollGenerated.v1")


@router.api_route("/api/v1/office/physical-claims", methods=["POST"], include_in_schema=False)
async def post_office_physical_claims(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Physical claim intake: register a paper claim, scan, data entry")


@router.api_route("/api/v1/office/transfers", methods=["GET"], include_in_schema=False)
async def get_office_transfers(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Form 13 transfers awaiting the DA's verification or the AO's decision")


@router.api_route("/api/v1/employers/me/transfer-requests", methods=["GET"], include_in_schema=False)
async def get_employers_me_transfer_requests(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Form 13 transfer requests awaiting attestation")


@router.api_route("/api/v1/members/me/claims", methods=["GET"], include_in_schema=False)
async def get_members_me_claims(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "List own claims")


@router.api_route("/api/v1/members/me/claims", methods=["POST"], include_in_schema=False)
async def post_members_me_claims(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Advance / partial withdrawal (purpose as sub-type)")


@router.api_route("/api/v1/members/me/transfers", methods=["POST"], include_in_schema=False)
async def post_members_me_transfers(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Transfer of PF between member IDs / exempted trusts")


@router.api_route("/api/v1/office/payment-scrolls/ready", methods=["GET"], include_in_schema=False)
async def get_office_payment_scrolls_ready(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Approved claims of the office ready for the next payment scroll (ledger debit posted, account not fr")


@router.api_route("/api/v1/office/system/cad-static-data", methods=["GET"], include_in_schema=False)
async def get_office_system_cad_static_data(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Diagnostic view of CAD static reference data (interest tables, bank branch master) and its version (")


@router.api_route("/api/v1/members/me/claims/eligibility-preview", methods=["GET"], include_in_schema=False)
async def get_members_me_claims_eligibility_preview(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Pre-flight: evaluate one form type before filing — eligible or not, blockers from account status, ma")


@router.api_route("/api/v1/members/me/claims/eligible-types", methods=["GET"], include_in_schema=False)
async def get_members_me_claims_eligible_types(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Available claim types with rule version and reasons (Journey B3)")


@router.api_route("/api/v1/members/me/tax/form-15g-15h", methods=["POST"], include_in_schema=False)
async def post_members_me_tax_form_15g_15h(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Upload Form 15G / 15H")


@router.api_route("/api/v1/members/me/claims/{claimId}", methods=["GET"], include_in_schema=False)
async def get_members_me_claims_claimId(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Claim detail + timeline (Journey B7)")


@router.api_route("/api/v1/members/me/transfers/{transferId}", methods=["GET"], include_in_schema=False)
async def get_members_me_transfers_transferId(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Transfer status")


@router.api_route("/api/v1/employers/me/transfer-requests/{transferId}/decisions", methods=["POST"], include_in_schema=False)
async def post_employers_me_transfer_requests_transferId_decisions(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Attest / reject transfer")


@router.api_route("/api/v1/members/me/claims/{claimId}/audit-trail", methods=["GET"], include_in_schema=False)
async def get_members_me_claims_claimId_audit_trail(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Post-submission: member's view of every state change on own claim (time, state, role, reason; office")


@router.api_route("/api/v1/members/me/claims/{claimId}/cancellations", methods=["POST"], include_in_schema=False)
async def post_members_me_claims_claimId_cancellations(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Cancel an unsettled claim (renamed from …/withdrawals; allowed only before a checker decision — see ")


@router.api_route("/api/v1/members/me/claims/{claimId}/confirmations", methods=["POST"], include_in_schema=False)
async def post_members_me_claims_claimId_confirmations(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Transaction-intent confirmation (Journey B3)")


@router.api_route("/api/v1/members/me/claims/{claimId}/documents", methods=["POST"], include_in_schema=False)
async def post_members_me_claims_claimId_documents(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Upload supporting document (PDF / JPEG / PNG up to 1 MB, content checked, SHA-256 kept; stored by cl")


@router.api_route("/api/v1/members/me/claims/{claimId}/re-disbursement-requests", methods=["POST"], include_in_schema=False)
async def post_members_me_claims_claimId_re_disbursement_requests(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Member submits corrected bank details after a payment return, without re-filing the claim")


@router.api_route("/api/v1/claimants/death-claims/{claimId}", methods=["GET"], include_in_schema=False)
async def get_claimants_death_claims_claimId(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Status (claimant verified separately; no member PII beyond entitlement)")


@router.api_route("/api/v1/claimants/death-claims/{claimId}/beneficiaries", methods=["POST"], include_in_schema=False)
async def post_claimants_death_claims_claimId_beneficiaries(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Inward an additional co-beneficiary / legal heir on an open death claim")


@router.api_route("/api/v1/office/annexure-k-files/{annexureId}/reconciliations", methods=["POST"], include_in_schema=False)
async def post_office_annexure_k_files_annexureId_reconciliations(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "ANNEXURE K RECO — match an inter-office Annexure K with the transfer and member records")


@router.api_route("/api/v1/office/claims/{claimId}/additional-forms", methods=["GET"], include_in_schema=False)
async def get_office_claims_claimId_additional_forms(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Additional Form Details — forms filed with a claim (e.g. a Joint Declaration): filed / initiated dat")


@router.api_route("/api/v1/office/claims/{claimId}/audit-trail", methods=["GET"], include_in_schema=False)
async def get_office_claims_claimId_audit_trail(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Full claim audit trail for officers and auditors: transitions, actor IDs, approval level, rule versi")


@router.api_route("/api/v1/office/claims/{claimId}/cad", methods=["GET"], include_in_schema=False)
async def get_office_claims_claimId_cad(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "View the latest Claim Approval Docket and every level's version")


@router.api_route("/api/v1/office/claims/{claimId}/cad", methods=["POST"], include_in_schema=False)
async def post_office_claims_claimId_cad(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Generate the Claim Approval Docket (CAD) at this level (CITES: the initiator, each verifier and the ")


@router.api_route("/api/v1/office/claims/{claimId}/payment-instructions", methods=["POST"], include_in_schema=False)
async def post_office_claims_claimId_payment_instructions(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Settlement payment instruction → PaymentInstructed.v1 (Journey B6)")


@router.api_route("/api/v1/office/claims/{claimId}/re-disbursement-approvals", methods=["POST"], include_in_schema=False)
async def post_office_claims_claimId_re_disbursement_approvals(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "APFC authorises a new payment after a return, without reopening adjudication")


@router.api_route("/api/v1/office/claims/{claimId}/reissues", methods=["POST"], include_in_schema=False)
async def post_office_claims_claimId_reissues(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Re-issue after bank return (Journey B6)")


@router.api_route("/api/v1/office/death-claims/{claimId}/shares-summary", methods=["GET"], include_in_schema=False)
async def get_office_death_claims_claimId_shares_summary(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Allocated vs legacy-settled vs disbursed vs pending share of a death claim")


@router.api_route("/api/v1/office/payment-scrolls/{scrollId}/return-reconciliations", methods=["POST"], include_in_schema=False)
async def post_office_payment_scrolls_scrollId_return_reconciliations(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Reconcile a bank return scroll, open re-settlement cases")


@router.api_route("/api/v1/office/transfers/{transferId}/decisions", methods=["POST"], include_in_schema=False)
async def post_office_transfers_transferId_decisions(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Process a Form 13 transfer between member IDs / offices")


@router.api_route("/api/v1/office/transfers/{transferId}/verifications", methods=["POST"], include_in_schema=False)
async def post_office_transfers_transferId_verifications(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "DA verifies service at both establishments before the AO decides")


@router.api_route("/api/v1/office/death-claims/{claimId}/beneficiaries/{beneficiaryId}/shares", methods=["PUT"], include_in_schema=False)
async def put_office_death_claims_claimId_beneficiaries_beneficiaryId_shares(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Amend a beneficiary's share (nominee deceased, court order, share already settled in legacy, guardia")
