"""GENERATED by packages/service-template/scaffold.py from docs/endpoint-catalogue.md — do not edit.

Phase-1 operations owned by this service. Until an operation is implemented, it verifies the caller's
internal token and answers 501 /problems/not-yet-built. Replace a stub by adding a real route with the
same method and path in app/api/routes.py; stubs are only registered for paths not already routed."""
from fastapi import APIRouter, Depends

from epfo_auth import Actor, require_actor
from epfo_observability import Problem

router = APIRouter()

OPERATIONS = ['GET /office/transfers', 'GET /employers/me/transfer-requests', 'GET /members/me/claims', 'POST /members/me/claims', 'POST /members/me/transfers', 'GET /members/me/claims/eligible-types', 'POST /members/me/tax/form-15g-15h', 'GET /members/me/claims/{claimId}', 'GET /members/me/transfers/{transferId}', 'POST /employers/me/transfer-requests/{transferId}/decisions', 'POST /members/me/claims/{claimId}/confirmations', 'POST /members/me/claims/{claimId}/re-disbursement-requests', 'POST /office/claims/{claimId}/payment-instructions', 'POST /office/claims/{claimId}/re-disbursement-approvals', 'POST /office/claims/{claimId}/reissues', 'POST /office/transfers/{transferId}/decisions', 'POST /office/transfers/{transferId}/verifications']

@router.api_route("/api/v1/office/transfers", methods=["GET"], include_in_schema=False)
async def get_office_transfers(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Form 13 transfers awaiting the DA's verification or the AO's decision")


@router.api_route("/api/v1/employers/me/transfer-requests", methods=["GET"], include_in_schema=False)
async def get_employers_me_transfer_requests(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Form 13 transfer requests awaiting attestation")


@router.api_route("/api/v1/members/me/claims", methods=["GET"], include_in_schema=False)
async def get_members_me_claims(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "List own claims")


@router.api_route("/api/v1/members/me/claims", methods=["POST"], include_in_schema=False)
async def post_members_me_claims(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Advance / partial withdrawal (purpose as sub-type)")


@router.api_route("/api/v1/members/me/transfers", methods=["POST"], include_in_schema=False)
async def post_members_me_transfers(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Transfer of PF between member IDs / exempted trusts")


@router.api_route("/api/v1/members/me/claims/eligible-types", methods=["GET"], include_in_schema=False)
async def get_members_me_claims_eligible_types(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Available claim types with rule version and reasons (Journey B3)")


@router.api_route("/api/v1/members/me/tax/form-15g-15h", methods=["POST"], include_in_schema=False)
async def post_members_me_tax_form_15g_15h(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Upload Form 15G / 15H")


@router.api_route("/api/v1/members/me/claims/{claimId}", methods=["GET"], include_in_schema=False)
async def get_members_me_claims_claimId(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Claim detail + timeline (Journey B7)")


@router.api_route("/api/v1/members/me/transfers/{transferId}", methods=["GET"], include_in_schema=False)
async def get_members_me_transfers_transferId(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Transfer status")


@router.api_route("/api/v1/employers/me/transfer-requests/{transferId}/decisions", methods=["POST"], include_in_schema=False)
async def post_employers_me_transfer_requests_transferId_decisions(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Attest / reject transfer")


@router.api_route("/api/v1/members/me/claims/{claimId}/confirmations", methods=["POST"], include_in_schema=False)
async def post_members_me_claims_claimId_confirmations(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Transaction-intent confirmation (Journey B3)")


@router.api_route("/api/v1/members/me/claims/{claimId}/re-disbursement-requests", methods=["POST"], include_in_schema=False)
async def post_members_me_claims_claimId_re_disbursement_requests(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Member submits corrected bank details after a payment return, without re-filing the claim")


@router.api_route("/api/v1/office/claims/{claimId}/payment-instructions", methods=["POST"], include_in_schema=False)
async def post_office_claims_claimId_payment_instructions(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Settlement payment instruction → PaymentInstructed.v1 (Journey B6)")


@router.api_route("/api/v1/office/claims/{claimId}/re-disbursement-approvals", methods=["POST"], include_in_schema=False)
async def post_office_claims_claimId_re_disbursement_approvals(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "APFC authorises a new payment after a return, without reopening adjudication")


@router.api_route("/api/v1/office/claims/{claimId}/reissues", methods=["POST"], include_in_schema=False)
async def post_office_claims_claimId_reissues(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Re-issue after bank return (Journey B6)")


@router.api_route("/api/v1/office/transfers/{transferId}/decisions", methods=["POST"], include_in_schema=False)
async def post_office_transfers_transferId_decisions(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Process a Form 13 transfer between member IDs / offices")


@router.api_route("/api/v1/office/transfers/{transferId}/verifications", methods=["POST"], include_in_schema=False)
async def post_office_transfers_transferId_verifications(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "DA verifies service at both establishments before the AO decides")
