"""GENERATED by packages/service-template/scaffold.py from docs/endpoint-catalogue.md — do not edit.

Phase-1 operations owned by this service. Until an operation is implemented, it verifies the caller's
internal token and answers 501 /problems/not-yet-built. Replace a stub by adding a real route with the
same method and path in app/api/routes.py; stubs are only registered for paths not already routed."""
from fastapi import APIRouter, Depends

from epfo_auth import Actor, require_actor
from epfo_observability import Problem

router = APIRouter()

OPERATIONS = ['GET /members/me/claims', 'POST /members/me/claims', 'GET /members/me/claims/eligible-types', 'GET /members/me/claims/{claimId}', 'POST /members/me/claims/{claimId}/confirmations', 'POST /office/claims/{claimId}/payment-instructions', 'POST /office/claims/{claimId}/reissues']

@router.api_route("/api/v1/members/me/claims", methods=["GET"], include_in_schema=False)
async def get_members_me_claims(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "List own claims")


@router.api_route("/api/v1/members/me/claims", methods=["POST"], include_in_schema=False)
async def post_members_me_claims(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Advance / partial withdrawal (purpose as sub-type)")


@router.api_route("/api/v1/members/me/claims/eligible-types", methods=["GET"], include_in_schema=False)
async def get_members_me_claims_eligible_types(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Available claim types with rule version and reasons (Journey B3)")


@router.api_route("/api/v1/members/me/claims/{claimId}", methods=["GET"], include_in_schema=False)
async def get_members_me_claims_claimId(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Claim detail + timeline (Journey B7)")


@router.api_route("/api/v1/members/me/claims/{claimId}/confirmations", methods=["POST"], include_in_schema=False)
async def post_members_me_claims_claimId_confirmations(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Transaction-intent confirmation (Journey B3)")


@router.api_route("/api/v1/office/claims/{claimId}/payment-instructions", methods=["POST"], include_in_schema=False)
async def post_office_claims_claimId_payment_instructions(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Settlement payment instruction → PaymentInstructed.v1 (Journey B6)")


@router.api_route("/api/v1/office/claims/{claimId}/reissues", methods=["POST"], include_in_schema=False)
async def post_office_claims_claimId_reissues(actor: Actor = Depends(require_actor)) -> None:
    raise Problem(501, "/problems/not-yet-built", "Not built yet", "Re-issue after bank return (Journey B6)")
